### PR TITLE
💈 Cell queued state

### PR DESCRIPTION
**Pull request by shashankp**

### CODE REVIEW

**Comment by fonsp** [comment]
Can you make it a draft PR?

**Comment by fonsp** [comment]
Looks awesome by the way! Happy that you figured out how to get that information from Julia to display.

**Comment by fonsp** [comment]
Have you experimented with using different animation speeds instead of colors?

**Comment by shashankp** [comment]
> Have you experimented with using different animation speeds instead of colors?

not sure if its making the difference obvious

animation

**Comment by fonsp** [comment]
I feel like this is much more clear than only showing a difference in colors. It's also because that particular choice of green and grey have the same luminosity, but in general i feel like giving it a color is semantically wrong. Green is "good", but that does not apply here.

Maybe we can do [fast]+[slightly dark gray] for the running cell, and [very slow]+[slightly lighter gray] for the rest?

**Comment by shashankp** [comment]
> I feel like this is much more clear than only showing a difference in colors. It's also because that particular choice of green and grey have the same luminosity, but in general i feel like giving it a color is semantically wrong. Green is "good", but that does not apply here.
> 
> Maybe we can do [fast]+[slightly dark gray] for the running cell, and [very slow]+[slightly lighter gray] for the rest?

agree.. better?

grayed

**Comment by fonsp** [comment]
Woa that gave me chills, very nice

**Comment by shashankp** [comment]
Will browse the issues & cherry pick, there are quite a few.
When I get stuck at figuring out the core pieces, we could have a video call

welcome & thank you for the neat project 
already has visibility from the MIT course; needs to keep the momentum to make it great!

**Comment by fonsp** [comment]
Great! Happy to help.

Tips for outreach/momentum are also welcome! Don't know much about this myself

**Pull request merged**
