### PR TITLE
📰 Preview in frontmatter editor

### PR DESCRIPTION
**Pull request by fonsp**
https://github.com/fonsp/Pluto.jl/assets/6933510/95e7d33c-78c1-403b-aaac-cb4e9aace1e2

### CODE REVIEW

**Comment by Pangoraw** [comment]
Nice! :sparkles: it would be pretty to cool to be able to embed this as [an og image](https://ogp.me/) in the static HTML export to have a preview when sharing a link to a notebook.

**Comment by fonsp** [comment]
With https://vercel.com/docs/functions/edge-functions/og-image-generation ! Seems really cool but also maybe too much work... Maybe @ctrekker is interested in adding this to glass one day?

**Comment by ctrekker** [comment]
Looks like a nice opportunity to make links cleaner when shared! Do you mind if I use the same card styling for published notebooks in Glass? The default behavior isn't very clean currently (see https://glassnotebook.io/r/R8vQF4q7Y08OyKT8Z3vvP/ for example), and it would be nice to mimic the card design language already used on the Pluto landing page

**Comment by fonsp** [comment]
Of course!! 💛

**Pull request merged**
