### PR TITLE
Set IOContext for redirected stdout/stderr

### LINKED ISSUE #2823: IOContext not properly set for `stdout`, disables ANSI colors
Since #2148 the `stdout` capture window supports ANSI terminal colors, and `:color => true` is set in `default_stdout_iocontext` as seen here:

https://github.com/fonsp/Pluto.jl/blob/216451c3c839d1c3c6c50a0b69ba1b8297cceb43/src/runner/PlutoRunner/src/PlutoRunner.jl#L1007-L1012

However, when querying `stdout` in a Pluto cell, `:color` is set to `false`, so well-behaved Julia code will not print colors. MWE: `printstyled("hello"; color=:red)`. A workaround is to wrap `stdout` in your own `IOContext` and set `:color => true`, but this should not be necessary.

image
(Please take this screenshot in place of a video. Nothing dynamic here.)

Notebook file: https://gist.github.com/danielwe/0663e49fbfb2219b2230d3fe2092c097

Using Pluto 0.19.39 on Julia 1.10.1

### PR DESCRIPTION
**Pull request by danielwe**
Fixes #2823 

No tests yet

### CODE REVIEW

**Comment by danielwe** [comment]
Tests added, loosely following the pattern in `test/Logging.jl`. The idea is to verify that every IOContext property set in `PlutoRunner.default_stdout_iocontext` is visible on `stdout` and `stderr` inside a notebook. (I included `stderr` because `PlutoRunner` sends both streams to the same pipe.) Let me know if this should be done differently.

**Comment by fonsp** [comment]
Thanks! Can you take a look at https://github.com/fonsp/Pluto.jl/pull/2727 and try to find a solution that works for both use cases?

**Comment by danielwe** [comment]
How about like this?

**Comment by fonsp** [comment]
Nice! This seems to match the REPL:

```
julia> IOContext(stdout).dict
Base.ImmutableDict{Symbol, Any} with 1 entry:
  :color => true

julia> struct ShowMyIO end

julia> Base.show(io::IO, m::MIME"text/plain", s::ShowMyIO) = @info "s" IOContext(io).dict

julia> ShowMyIO()
┌ Info: s
│   (IOContext(io)).dict =
│    Base.ImmutableDict{Symbol, Any} with 4 entries:
│      :module                => Main
│      :limit                 => true
│      :last_shown_line_infos => Tuple{String, Int64}[]
└      :color                 => true

```

**Comment by fonsp** [comment]
Could you write the tests in a more end-to-end style? Right now the test is very exact for the question: "did the IO context get set properly"? What I would prefer to test is whether the two issues are fixed:
- Does `printstyled` work? 
- Does `show(bigarray)` and `show(stdout, bigarray)` and `show(stdout, "text/plain", bigarray)` show the full array contents? (e.g. check if the middle element occurs in the string)
- Does `display(bigarray)` limit the display?

It would also be nice if the tests are added to the existing notebook in test/Logging.jl, this makes the tests run faster because no new process needs to be started.

**Comment by fonsp** [comment]
PS Thanks again! Nice implementation :)

**Comment by fonsp** [comment]
@danielwe Hey! Do you have time to take a look at the tests?

**Comment by danielwe** [comment]
Thanks for the feedback! I'm rather strapped for time at the moment. I can probably look at it next week, but if someone wants to adopt this to get it across the finish line sooner, feel free!

**Comment by fonsp** [comment]
anyone should feel free to finish this! just fork the fork :)

**Comment by ReubenJ** [comment]
I've created some end-to-end style tests to cover the cases you mentioned, @fonsp. What's the best way to incorporate these? Just open a new PR?

**Comment by danielwe** [comment]
I just gave you write access to my fork, @ReubenJ, so you can continue using this PR if you wish. Thanks so much for taking this on! When I said "next week" I must have meant next year...

**Comment by danielwe** [comment]
Just push your commits to the `stdoutiocontext` branch in my fork

**Comment by fonsp** [comment]
Nice! Could you test all three forms? show(bigarray) and show(stdout, bigarray) and show(stdout, "text/plain", bigarray)

**Comment by ReubenJ** [comment]
Looks like just one of the Throttled tests is failing. Should be all set otherwise!

**Comment by fonsp** [comment]
Thanks @ReubenJ, amazing!!

Looking forward to your next contribution! Maybe https://github.com/fonsp/Pluto.jl/issues/2417 ? :)

**Comment by ReubenJ** [comment]
Sure thing. I won't have time until a couple of weeks from now, but I'd be happy to then.

**Comment by danielwe** [comment]
Fantastic! :rocket:

**Pull request merged**
