### PR TITLE
Cell output changed event

### PR DESCRIPTION
**Pull request by shashankp**
Companion to https://github.com/fonsp/PlutoUI.jl/pull/30
Needed for https://github.com/fonsp/Pluto.jl/issues/307
Uses window level CustomEvents
to trigger rendering of TableOfContentsElement after html elements are rendered.

_Note: doesnt work for cell delete scenario_

### CODE REVIEW

**Comment by fonsp** [comment]
We don't need to pass callbacks from the Editor to the RawHTMLContainer, the event can be dispatched directly by the RwHTMLContainer. Also, it looks like the event is never fired?

**Comment by dralletje** [comment]
I agree with @fonsp.
I do understand the way that the callback has to travel up the tree to get a reference to `cell`, but I like the idea of going with vanilla javascript fully.

I'd say we do the dispatching from the Cell component, so we can still add the `cell` as detail, but it's not in the oh-so-big Editor.js file.

Also then we can dispatch the event from the actually pluto html node 
```
let cell_element_ref = useRef();
<pluto-cell
  ref=${cell_element_ref}
  on_render=${() => cell_element_ref.dispatchEvent( ... )}
```
this feels a lot cleaner and allows for a lot more control (the handler can get the actual cell element, stuff with bubbling?)

**Comment by fonsp** [comment]
Giving the entire `cell` as event detail is nice, but on the other hand, we don't want people to depend on its structure if we want to change it later. (I do)

**Comment by dralletje** [comment]
I'm working on a small rewrite of the html rendering stuff, and I'll put  this in as well. Is there a way to add someone as a collaborator to a commit? Feels bad to take part of your code and erase your name from it 😂 @shashankp

**Comment by shashankp** [comment]
@dralletje can do git gymnastics with multiple remotes, but I'd say don't worry: more commits coming from me 😁

**Comment by fonsp** [comment]
The `cell_output_changed` event is never fired, right?

I think we should not have an `on_delete` event, because it is only useful if the JS code that depends on that event is keeping an internal notebook state. We should design our API such that this is not necessary.

A better option is to fire the same `cell_output_changed` event after setting the `innerHTML` to `""`. We can think about custom events for notebook state updates later.

**Comment by fonsp** [comment]
Another comment: do we need to fire this event ourselves? Is the built-in [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) not right for this?

**Comment by shashankp** [comment]
> The `cell_output_changed` event is never fired, right?

It does get fired in RawHtmlContainer > execute_scripttags 

> I think we should not have an `on_delete` event, because it is only useful if the JS code that depends on that event is keeping an internal notebook state. We should design our API such that this is not necessary.

> Another comment: do we need to fire this event ourselves? Is the built-in [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) not right for this?

Haven't looked into this, will check it 👍
hopefully it will help with cell rearrange

**Comment by dralletje** [comment]
MutationObserver is too low level for this stuff, also don't think you can get this behavior specifically, or it would break really quick when we change anything about the html structure.

**Comment by shashankp** [comment]
I see if MutationObserver is used, then the TableOfContents element needs to listen to changes on notebook (or only markdown cells?) & this PR isn't needed. But having all these events being sent to it might effect performance in cases of live data changes like a slider.

**Comment by dralletje** [comment]
I made it work with only a mutation observer. Let's see if that works first 😁
I'll close this PR in the meantime.

**Pull request closed without merging**
