### PR TITLE
Update & format tests, add patch recovery code

### PR DESCRIPTION
**Pull request by pankgeorg**
Simple, boring,maintenance PR where

- reformat tests
- handle old version string (click the alert) #951 
- when `applyPatch` fails to apply patches, try to recover (request and apply the state as whole)
- update puppeteer code _not_ to use [deprecated waitFor function](https://github.com/puppeteer/puppeteer/issues/6214)

### CODE REVIEW

**Comment by pankgeorg** [comment]
TODO:

- [ ] There is some code that recovers from failed `applyPatches`. Even though that's nice for the users, the front-end tests _should never pass_ if that code runs.

**Comment by fonsp** [comment]
Great, thanks! I skimmed it, I don't think you need me to review this right?

**Comment by pankgeorg** [comment]
These 3 things are FYI:
- On [applyPatches](https://github.com/fonsp/Pluto.jl/pull/963/files#diff-d0b76cc753bebaa7bbde63848adae9617f1e69dd9cd9986b98b7a3c5e39fc02bR494) fail
- we request a [fresh](https://github.com/fonsp/Pluto.jl/pull/963/files#diff-0c766bc02bcf204861a3849cc4b55c96bb230c5126254b52c340ecdeb2a89b56R3400) [state](https://github.com/fonsp/Pluto.jl/pull/963/files#diff-0c766bc02bcf204861a3849cc4b55c96bb230c5126254b52c340ecdeb2a89b56R138)
- and try to [apply](https://github.com/fonsp/Pluto.jl/pull/963/files#diff-d0b76cc753bebaa7bbde63848adae9617f1e69dd9cd9986b98b7a3c5e39fc02bR456) it back

PlutoErrors like this will be transparent to users but [frontend tests will fail](https://github.com/fonsp/Pluto.jl/pull/963/files#diff-d8416c292d77c64ecf2ebf49ec5489190e3120f02416a74e17c02aaf86c7c6acR68)

**Comment by pankgeorg** [comment]
Added an alert and a copy paste friendy message in the console:
image

**Pull request merged**
