### PR TITLE
Make sure cells don't use top-level return

### PR DESCRIPTION
**Pull request by dralletje**
A tiny wrapper in the timed_expr/trycatch_expr - wanted to make it more sound logicy (separate functions composed) but that felt like it was going to make it more complex.
So I find this suffices for now :D

### CODE REVIEW

**Comment by fonsp** [comment]
Can you add a test?

**Comment by dralletje** [comment]
@fonsp tests added

**Comment by dralletje** [comment]
Lekker

**Comment by dralletje** [comment]
Aaait

**Pull request merged**
