### PR TITLE
add keyboard shortcuts (LeftArrow and RightArrow) to move slides in presentation mode

### PR DESCRIPTION
**Pull request by disberd**
Thanks to @fonsp for showing me the React way

When in presentation mode, using the Left and Right arrow will allow to move slides back and forward.
This functionality is not triggered when the active element is a cell input or any other element within the notebook that you might want to interact with using arrows.

Also added some experimental functionality to detect full screen and prompt for activating (or deactivating) presentation mode:

https://github.com/fonsp/Pluto.jl/assets/12846528/90ecd33d-07fc-4484-91d7-13bf0d4d7826

There are some caveats to the current automatic detection of full screen:
- It does not work on chrome if the browser zoom level is not 100%
  - This is because chrome does not the update the `screen.height` as a function of the zoom and there does not seem to be a nice way to make it work reliably
- The popup does not disappear if clicking outside of it (this is caused by `source_element =  null` in the `open_popup` function.  @fonsp is there a better way/source_element to handle this?

### CODE REVIEW

**Comment by disberd** [comment]
Maybe is better to add a keyboard shortcut for presentation mode and avoid the automatic full screen detection? So the user that wants to present can explicitly do so (without having to open the developer console) using a shortcut and also manually trigger fullscreen.

Any thoughts on this @fonsp?

**Comment by pankgeorg** [comment]
> Maybe is better to add a keyboard shortcut for presentation mode and avoid the automatic full screen detection? So the user that wants to present can explicitly do so (without having to open the developer console) using a shortcut and also manually trigger fullscreen.

I would agree to avoid fullscreen detection. Let's try using the [official API](https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenElement) or avoid it altogether.

Also since we're adding shortcuts, may I also suggest:
- Page Up / Down (= ⬅️➡️)
- Escape (exit presentation mode)
- Space (= ➡️)

**Comment by disberd** [comment]
Thanks for the feedback @pankgeorg.

I will implement the additional shortcuts and remove the full screen detection. Unfortunately the fullscreen API was my first attempt but it only works reliably when full-screen is triggered programmatically (on windows F11 seems to be handled by OS so it does not trigger the event from the fullScreen API).

Regaring a short-cut to manually enter presentation mode, you got any suggestion on what key combination to use?
something F5 related would make it similar to powerpoint, but I think F5 behavior might be already something else in many use cases...

**Comment by fonsp** [comment]
Looks good @disberd ! What's left to finish this PR?

**Comment by fonsp** [comment]
Let's merge the keyboard shortcuts and discuss the activation in a Discussion? I also think detection based on viewport height or the Fullscreen API are not working great, even though that would be very nice to use.

**Comment by disberd** [comment]
@fonsp OK, I'll clean up the code in the next days to remove the automatic full-screen detection

**Comment by disberd** [comment]
@fonsp this should be ready to go (removed the full screen detection and added shortcuts suggested by @pankgeorg)

**Comment by fonsp** [comment]
woohooo

look forward to the next react PR @disberd!

**Comment by fonsp** [comment]
the fullscreen detection was well implemented btw (with usestate and useeffect etc), just tricky with all the platforms behaving differently

**Pull request merged**
