### PR TITLE
Update notebook from file with popup

### PR DESCRIPTION
**Pull request by disberd**
Very much inspired in functionality by https://github.com/fonsp/Pluto.jl/pull/1029, but instead of automatically reloading from file, provide a small disclaimer on the notebook (basically copied in style from the one reminding you to save updates when modifying a notebook) that actually reload the notebook from the file upon click.

I did implement this small modification as sometime I had issues with too many updates from file with the greedy update from https://github.com/fonsp/Pluto.jl/pull/1029.

Here is an example functionality:
update_from_file_example

Let me know if this is something that might be considered interesting or if I will simply just keep it on my fork

Still to do:
- [x] Track notebook file movement from Pluto
- [x] Maybe have a configuration option to always do greedy reload without waiting for feedback
- [ ] Implement throttle for greedy update as suggested by @fonsp
- [ ] Handle cell deletion from file
- [ ] Handle cell addition from file

Edit: Added configuration option to default to greedy reload instead of waiting for confirmation. Can be enabled doing
```julia
Pluto.run(;auto_reload_notebook_from_file=true)
```

### CODE REVIEW

**Comment by fonsp** [comment]
This is fantastic! Some ideas:
- We should try to keep unsubmitted code changes in the browser. This probably works already?
- I am thinking that we might want to *always* update from file, without asking the user, like in #1029, but use your new UI to tell the user what happened. This fits the "reactive magic" of Pluto, and I think that this is the best option for beginner users.
- What happens when the notebook file changes into something invalid? It would be great if we would tell the user.

We can discuss here or on our call tomorrow!

**Comment by fonsp** [comment]
We could address the greedy update in #1029 using a throttle: when the file changes, 
1. read its new contents
2. wait 200ms
3. read its contents
4. if the last two read contents are not equal, go back to 2
5. update notebook

**Comment by disberd** [comment]
> This is fantastic! Some ideas:
> 
> * We should try to keep unsubmitted code changes in the browser when reloading from file. This probably works already?
> * I am thinking that we might want to _always_ update from file, without asking the user, like in [Watch notebook file for changes #1029](https://github.com/fonsp/Pluto.jl/pull/1029), but use your new UI to tell the user what happened. This fits the "reactive magic" of Pluto, and I think that this is the best option for beginner users.
> * What happens when the notebook file changes into something invalid? It would be great if we would tell the user.
> 
> We can discuss here or on our call tomorrow!

Thanks for the feedback!

Regarding your points:
1. I do not think this already works (I didn't implement the reload from file so I don't remember now but I think i just overwrites the editor with the file contents at the moment).
2. I agree that this is probably the best default approach
3. By invalid you mean from the Pluto file synthax (like making a modification that breaks the Pluto parsing of the file?), I suppose that could be easy to detect and warn about

**Comment by greimel** [comment]
When I modify notebooks in an editor my most common problem is that the uuids at the bottom get out of sync with the code cells. It would be nice if this got handled gracefully. (This also happened frequently when I commited indivual hunks in git and then stashed.)

(Tbh, I haven't this in a while, so I am not sure if this issue is already fixed.)

**Comment by disberd** [comment]
> When I modify notebooks in an editor my most common problem is that the uuids at the bottom get out of sync with the code cells. It would be nice if this got handled gracefully. (This also happened frequently when I commited indivual hunks in git and then stashed.)
> 
> (Tbh, I haven't this in a while, so I am not sure if this issue is already fixed.)

Do you mean when you were deleting cells alltogether without updating the bottom cell order or in general when just changing code from within one cell?
If it's the latter, I think I never experienced this as a problem.

Regarding instead deleting or adding cells all-together within the notebook from the file would be a nice improvement.

- Deleting cells should not be too difficult (I suppose but I'd have to check), we would just have to make sure that one does not break up dependencies with other non deleted cells when doing so but that should be verifiable using the cell dependency tree.
- Adding a new cell is something that instead I found myself wanting to do more often and having to go through the notebook to do is inconvenient. One of the issues here is probably where to put the cell on the front-end once this is inserted from the file, given tht the file cell orders are different from the display order on the notebook

**Comment by greimel** [comment]
> Do you mean when you were deleting cells alltogether without updating the bottom cell order

Yes, that's what I meant.

> Regarding instead deleting or adding cells all-together within the notebook from the file would be a nice improvement.

Yes!

> One of the issues here is probably where to put the cell on the front-end once this is inserted from the file

I think displaying the new cell just below the previous cell would be a good enough default. Don't you think? 

It would be nice to get a pop-up when a new cell is added to jump to this cell in the browser.

Would be nice if the following issues would be handled as well:
* if you copy-paste a cell in the source (leading duplicate uuid)
* if the new uuid is too short or too long or missing

don't error, just assign a new uuid.

**Comment by fonsp** [comment]
These two new features: an easy way to delete or add cells from a text editor, requires some extra thinking and design, and I think we should do that in a separate PR. Let's get this PR ready and merged first, so that Pluto will work more smoothly together with git.

**Comment by greimel** [comment]
Alright. But since you're making the point

>  so that Pluto will work more smoothly together with git.

I want to note that adding/deleting cells is an important feature for working smoothly with git. (In fact, I never edit notebooks in an editor.) 

Committing individual code blocks ("hunks") is very easy with modern git GUIs. And this doesn't play well with Pluto because the notebook doesn't load when the uuid list is out of sync with the code cells.

But I agree that this is a separate issue.

**Comment by fonsp** [comment]
Thanks @disberd ! I used your idea to implement a pop-up message in #1029 

https://user-images.githubusercontent.com/6933510/134787985-259ddaff-3eca-4670-8d8b-c1884bc766f2.mov

**Comment by disberd** [comment]
Thanks for taking the lead @fonsp, I am quite backlogged at work so I didn't have time to proceed yet :D

**Pull request closed without merging**
