### PR TITLE
🎞 Built-in Tables - interactive viewer

### LINKED ISSUE #292: Display DataFrame with more than 18 rows/columns
For larger DataFrames, are the first 18 rows and columns are displayed in Pluto.
Is there a way to increase this number?
I already tried the "standard methods" suggested by DataFrames.jl: setting the COLUMNS and LINES environment variables or using `show`, but without success.

```
using DataFrames

ENV["COLUMNS"]=1000
ENV["LINES"] = 50
# method that works in REPL / IJulia,  but seems to have no effect in Pluto
# https://juliadata.github.io/DataFrames.jl/stable/man/getting_started/#Installation

df = hcat([DataFrame(a=1:30, b=2:31) for _ in 1:10]..., makeunique=true)
# only 18 rows and 18 columns are displayed (the df size is 30x20)

show(df, allrows=true, allcols=true) # prints on the server side, but not in the notebook
```

Could you please help?

### PR DESCRIPTION
**Pull request by fonsp**
DataFrames will now show more rows and columns by default, in a scrollable view. More rows and columns can be loaded by clicking More. (Works with DataFrames, or any other `Tables.jl`-compatible table.)

dataframelazyload

# How to test out this branch

```julia
julia> ]
(v1.5) pkg> add Pluto#built-in-tables
julia> import Pluto; Pluto.run()
```

Then use a notebook with DataFrames as usual!

When you're done, go back to the registered version of Pluto, to make sure that you get the latest updates after this PR is done:
```julia
(v1.5) pkg> rm Pluto
(v1.5) pkg> add Pluto
```

# PR notes

To fix #292 

TODO:
- [x] Lots of stuff
- [x] Lazy load rows
- [x] Truncate columns
- [x] See how much the loading time is affected by adding the dependency. Investigate Requires.jl if it is too much
- [x] Scroll correction too much with overflowing rows
- [ ] the "... more" button for rows should stretch all columns

Can be added later:
- [x] Lazy load columns
- [x] Prettier schema

### CODE REVIEW

**Comment by fonsp** [comment]
Interactive inspector works inside tables!

image

**Comment by fonsp** [comment]
image

**Comment by lungben** [comment]
Looks great!

Maybe there is some synergy (in one way or the other) with the PrettyTables.jl html backend?
https://discourse.julialang.org/t/help-testing-prettytables-v0-10-0/49609

**Comment by fonsp** [comment]
Yeah I did think about it, but the HTML part of this PR is really just to generate the most basic possible HTML table:
```
<table>
<thead>
${schema}
</thead>
<tbody>
<tr>${rowdata}</tr>
...
</tbody>
```

And the big advancement is that this is done _in the frontend_, as part of Pluto, allowing for the "Show more" button when rows are truncated, images inside the table, etc.

I like PrettyTables.jl - love their commit messages 💕 - but the focus there is to get the best possible experience under the restriction that you are using a terminal, we don't have that restriction.

**Comment by lungben** [comment]
Are you applying some sort of cut-off to the data transfered to the front-end? I sometimes have DataFrames of GB size.

**Comment by fonsp** [comment]
yep

**Comment by fonsp** [comment]
#### Before

Procmpile: 2.8
Run notebook: 8.548534 seconds

#### after

Precmopuile: 2.95
Run notebook: 8.616516 second

**Comment by lungben** [comment]
Just tried it, looks great!

For a DataFrame view, it currently gives an error message:

```
df_view = @view df[df.a .% 2 .== 0, :]

Failed to show value:

MethodError: Cannot `convert` an object of type

DataFrames.DataFrameRow{DataFrames.DataFrame,DataFrames.Index{}} to an object of type

DataFrames.DataFrameRow{DataFrames.SubDataFrame{DataFrames.DataFrame,DataFrames.Index,Array{Int64,1}},DataFrames.Index{}}

Closest candidates are:

convert(::Type{S}, !Matched::T) where {S, T<:CategoricalArrays.CategoricalValue} at C:\Users\d90394\.julia\packages\CategoricalArrays\0ZAbp\src\value.jl:68

convert(::Type{T}, !Matched::T) where T at essentials.jl:171

setindex!(::Array{DataFrames.DataFrameRow{DataFrames.SubDataFrame{DataFrames.DataFrame,DataFrames.Index,Array{Int64,1}},DataFrames.Index},1}, ::DataFrames.DataFrameRow{DataFrames.DataFrame,DataFrames.Index}, ::Int64)@array.jl:847
macro expansion@multidimensional.jl:772[inlined]
macro expansion@cartesian.jl:64[inlined]
macro expansion@multidimensional.jl:767[inlined]
_unsafe_getindex!@multidimensional.jl:762[inlined]
_unsafe_getindex@multidimensional.jl:757[inlined]
_getindex@multidimensional.jl:743[inlined]
getindex(::DataFrames.DataFrameRows{DataFrames.SubDataFrame{DataFrames.DataFrame,DataFrames.Index,Array{Int64,1}},DataFrames.Index}, ::UnitRange{Int64})@abstractarray.jl:1060
table_data(::DataFrames.SubDataFrame{DataFrames.DataFrame,DataFrames.Index,Array{Int64,1}}, ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}})@PlutoRunner.jl:607
show_richest(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Any)@PlutoRunner.jl:378
#sprint_withreturned#23(::IOContext{Base.DevNull}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::DataFrames.SubDataFrame{DataFrames.DataFrame,DataFrames.Index,Array{Int64,1}})@PlutoRunner.jl:333
#format_output_default#13(::Pair{Symbol,Dict{Tuple{UInt64,Int64},Int64}}, ::typeof(Main.PlutoRunner.format_output_default), ::Any)@PlutoRunner.jl:268
#format_output#14@PlutoRunner.jl:285[inlined]
formatted_result_of(::Base.UUID, ::Bool, ::Nothing)@PlutoRunner.jl:76
top-level scope@none:1
```

Would it be possible to make the table viewer also working for views (like the default one)?

**Comment by fonsp** [comment]
@lungben Can you send me a table for which it doesn't work?

**Comment by fonsp** [comment]
I have [posted this to zulip](https://julialang.zulipchat.com/#narrow/stream/243342-pluto.2Ejl/topic/Test.20new.20DataFrames.20support/near/216134260) to get feedback before we merge

**Comment by fonsp** [comment]
From @lungben on zulip:
> would it be possible to "freeze" the column headers so that they are always visible when you scroll down?

**Comment by pankgeorg** [comment]
> From @lungben on zulip:
> 
> > would it be possible to "freeze" the column headers so that they are always visible when you scroll down?
👍🏾  on that

`position: sticky` can do the trick in 4 lines:
move `class="scroll_y"` to the `div` wrapper of `table`, apply `position: sticky; top: 0`; to the `th`s!

**Comment by fonsp** [comment]
@pankgeorg great! I experimented but didn't get it to work, could you send the code?

One reason why I add the class to `pluto-output` is so that `overflow-x: auto` and `overflow-y: auto` are set on the same element, which makes the scrollbars look nicer, and in my case my trackpad handles the 2D scrolling better.

**Comment by pankgeorg** [comment]
> @pankgeorg great! I experimented but didn't get it to work, could you send the code?
> 
> One reason why I add the class to `pluto-output` is so that `overflow-x: auto` and `overflow-y: auto` are set on the same element, which makes the scrollbars look nicer, and in my case my trackpad handles the 2D scrolling better.
> 
> Maybe to make sticky work, we can instead move the `overflow-x: auto` inwards?

this cell makes scrolling below it -- not 4 lines, not production ready code, but it does the trick.

Issues: visibility of `schema-types`, overlaps at top-left corner.
```
html"<style>
	pluto-output:not(.rich_output) {
		max-height: unset;
		overflow-y: unset;
		overflow-x: unset;
	}
	pluto-output.scroll_y > div{
		max-height: 80vh;
		width: 100%;
		overflow: auto;

	}
	.pluto-table .schema-names th{
		background-color: white;
		position:sticky;
		top: -1rem;
		z-index: 1;
	}

	.pluto-table tbody th:first-child{
		background-color: white;
		position:sticky;
		left: 0;
		top: 3rem;
	}
</style>"```

**Comment by fonsp** [comment]
It is not (yet) enabled for Tables.jl-implementors that do not have `rowaccess` - they still use the old display method. Let's leave it until someone finds this problem in the real world.

**Pull request merged**
