### PR TITLE
Fix #1322

### LINKED ISSUE #1322: Error: failed to add/remove packages, could not parse compatibility version
Reproduce: add `using Git_jll` cell to the notebook, execute it. The package doesn't get added, and errors appear in the console:
```
┌ Warning: PlutoPkg: Failed to add/remove packages! Resetting package environment...
│   PLUTO_VERSION = v"0.15.1"
│   VERSION = v"1.6.1"
│   old_packages =
│    1-element Vector{String}:
│     "Git_jll"
│   new_packages =
│    1-element Vector{String}:
│     "Git_jll"
│   exception =
│    Could not parse compatibility version for dependency `Git_jll`
│    Stacktrace:
│      [1] pkgerror(msg::String)
│        @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:55
│      [2] read_project_compat(raw::Dict{String, Any}, project::Pkg.Types.Project)
│        @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/project.jl:66
│      [3] Pkg.Types.Project(raw::Dict{String, Any})
│        @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/project.jl:121
│      [4] read_project(f_or_io::String)
│        @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/project.jl:136
│      [5] Pkg.Types.EnvCache(env::String)
│        @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:266
│      [6] load_ctx
│        @ ~/.julia/packages/Pluto/HmZoH/src/packages/PkgCompat.jl:64 [inlined]
│      [7] load_ctx(original::Pkg.Types.Context)
│        @ Pluto.PkgCompat ~/.julia/packages/Pluto/HmZoH/src/packages/PkgCompat.jl:71
│      [8] _modify_compat(f!::Pluto.PkgCompat.var"#22#23"{Pkg.Types.Context}, ctx::Pkg.Types.Context)
│        @ Pluto.PkgCompat ~/.julia/packages/Pluto/HmZoH/src/packages/PkgCompat.jl:391
│      [9] write_auto_compat_entries
│        @ ~/.julia/packages/Pluto/HmZoH/src/packages/PkgCompat.jl:402 [inlined]
...
```
Looks like, Pluto doesn't write a correct compat entry for package versions that include a build number: e.g., `Git_jll v2.31.0+0`. Relevant code is around https://github.com/fonsp/Pluto.jl/blob/28e452bc0582bb53c25768e02169a65ffa436e99/src/packages/PkgCompat.jl#L407.

### PR DESCRIPTION
**Pull request by aplavin**
continuation of https://github.com/fonsp/Pluto.jl/pull/1323 - cannot edit that one

### CODE REVIEW

**Comment by aplavin** [comment]
Don't think frontend tests failing are related?

**Comment by fonsp** [comment]
Thanks @aplavin !

**Comment by fonsp** [comment]
I believe that the new tests don't test your fix. (Uncomment your fix and run the new tests to verify.)

We currently have no test for:
1. New notebook
2. Import a (jll) package
3. Save & shut down notebook
4. Open notebook file and verify that the package env was loaded correctly.

Adding a `_jll` package to this test would be the way to verify your fix.

It would be awesome if you could take a shot at adding this test, but don't feel obligated to do so, since it would probably be a lot more work than you expected to contribute with this PR.

**Comment by aplavin** [comment]
I cannot easily check that now, but I believe the new test failed without my fix. Surprised that’s not the case.

**Pull request merged**
