### PR TITLE
Add a benchmark for compilation times

### PR DESCRIPTION
**Pull request by rikhuijzer**
Want meten is weten (because measuring is knowning). I've tried to do something fancy like https://github.com/rikhuijzer/PrecompileMacro.jl/issues/1, but that will take some (a lot of) time to make. So, as a first step, this PR just adds a separate benchmark for compilation time. I think that I've missed a lot of entry points, but I hope that once we are able to pin down what spots are compiled exactly, then we can start making progress on improving the performance.

### CODE REVIEW

**Comment by rikhuijzer** [comment]
A don‘t merge this. I have an idea. Using a new process for each benchmark should work.

**Comment by rikhuijzer** [comment]
Yeah, this is nice now. See the logs, there it shows:

```
5×3 DataFrame
 Row │ Operation                Allocations (MB)  Time (seconds)
     │ String                   Float64           Float64
─────┼───────────────────────────────────────────────────────────
   1 │ using Pluto                          75.3             0.9
   2 │ Pluto.ServerSession()                13.2             0.1
   3 │ SessionActions.open                 919.1             9.7
   4 │ SessionActions.shutdown              29.4             0.3
   5 │ SessionActions.new                   42.8             0.4
```

**Comment by rikhuijzer** [comment]
I've added `precompile` directives to the other entrypoints inside `SessionActions`. I wasn't able to use `PrecompileMacro.jl` because it gave very weird errors. Adding the precompile directives show some improvements on the allocations in the logs:

```
5×3 DataFrame
 Row │ Operation                Allocations (MB)  Time (seconds)
     │ String                   Float64           Float64
─────┼───────────────────────────────────────────────────────────
   1 │ using Pluto                          76.5             0.8
   2 │ Pluto.ServerSession()                13.2             0.2
   3 │ SessionActions.open                 897.4            10.4
   4 │ SessionActions.shutdown              18.8             0.3
   5 │ SessionActions.new                   16.9             0.4
```

Don't take these times too seriously. This run was on a particularly slow runner. Look at allocations.

I guess this provides a good idea of the tradeoff between running time and adding these directives. In this case, the 3 extra directives save 0.4 seconds in total or so on my pc.

**Comment by rikhuijzer** [comment]
I switched to `TimerOutputs.jl` thanks to a suggestion from David Widmann in another PR. This makes the output look as follows:

```
───────────────────────────────────────────────────────────────────
                                         Time          Allocations
                                   ───────────────   ───────────────
          Total measured:               45.1s            2.07GiB

 Section                   ncalls     time    %tot     alloc    %tot
 ───────────────────────────────────────────────────────────────────
 using Pluto                    1    588ms    5.3%   71.3MiB    7.8%
 Pluto.ServerSession()          1    175ms    1.6%   12.6MiB    1.4%
 SessionActions.open            1    9.78s   87.7%    797MiB   87.2%
 SessionActions.shutdown        1    260ms    2.3%   17.8MiB    1.9%
 SessionActions.new             1    350ms    3.1%   15.4MiB    1.7%
 ───────────────────────────────────────────────────────────────────
```
The CI job is going into an infinite loop it seems, but I have no idea why. Locally, it works fine

**Comment by rikhuijzer** [comment]
@fonsp This is what I'm referring to in the other comment (which I cannot link to because it's minimized). I'm a bit hesistant to open an issue because all info is here in the PR.

When opening the notebook in that PR, I see the following error while the task is being stuck:

```
Unkown error during eval_format_fetch_in_workspace
ex
TaskFailedException
task
Task (failed) @0x00007f5ea6474fe0
MethodError: no method matching run_expression(::Module, ::Expr, ::Base.UUID, ::Nothing, ::Nothing; user_requested_run=true, capture_stdout=false)
Closest candidates are:
  run_expression(::Module, ::Any, ::Base.UUID, ::Union{Nothing, Tuple{Set{Symbol}, Set{Symbol}}}, ::Union{Nothing, UInt64}; user_requested_run) at ~/.julia/packages/Pluto/2DPK4/src/runner/PlutoRunner.jl:454 got unsupported keyword argument "capture_stdout"
  run_expression(::Module, ::Any, ::Base.UUID, ::Union{Nothing, Tuple{Set{Symbol}, Set{Symbol}}}) at ~/.julia/packages/Pluto/2DPK4/src/runner/PlutoRunner.jl:454 got unsupported keyword arguments "user_requested_run", "capture_stdout"
  run_expression(::Module, ::Any, ::Base.UUID) at ~/.julia/packages/Pluto/2DPK4/src/runner/PlutoRunner.jl:454 got unsupported keyword arguments "user_requested_run", "capture_stdout"
Stacktrace:
 [1] kwerr(::NamedTuple{(:user_requested_run, :capture_stdout), Tuple{Bool, Bool}}, ::Function, ::Module, ::Expr, ::Base.UUID, ::Nothing, ::Nothing)
   @ Base ./error.jl:163
 [2] top-level scope
   @ none:1
 [3] eval
   @ ./boot.jl:373 [inlined]
 [4] (::Distributed.var"#167#168"{Module, Expr})()
   @ Distributed ./task.jl:423
```

With this error, and information about the day, I suspect that my freeze (which might be also the same as the first comment in this issue) is caused by https://github.com/fonsp/Pluto.jl/pull/1957.

EDIT: This error is very surprising because it shows the error in `~/.julia/packages/Pluto/` while I'm running `~/git/Pluto.jl/`. It looks like the newest version that I'm running calls an older version which is also what's causing the incompatible method signatures.

**Comment by fonsp** [comment]
I made https://github.com/JuliaPackaging/RelocatableFolders.jl/pull/15 about this. Did you switch git branches?

**Comment by rikhuijzer** [comment]
> I made [JuliaPackaging/RelocatableFolders.jl#15](https://github.com/JuliaPackaging/RelocatableFolders.jl/pull/15) about this. Did you switch git branches?

Yeah sure that could be it. I'll retry once that PR is merged :+1:

**Comment by rikhuijzer** [comment]
This is how the output looks now:

```
 ─────────────────────────────────────────────────────────────────────
                                           Time          Allocations
                                     ───────────────   ───────────────
           Total measured:                 740s            14.0GiB

 Section                     ncalls     time    %tot     alloc    %tot
 ─────────────────────────────────────────────────────────────────────
 import Pluto                     1    459ms    0.1%   66.0MiB    0.5%
 compiletimes.jl                  1    24.7s    3.4%   2.10GiB   15.3%
   SessionActions.open            1    12.5s    1.7%   1.14GiB    8.3%
   SessionActions.shutdown        1    563ms    0.1%   71.5MiB    0.5%
 Events.jl                        1    4.58s    0.6%    405MiB    2.9%
 WorkspaceManager.jl              1    93.3s   12.7%   1.01GiB    7.4%
 packages/Basic.jl                1     148s   20.1%    878MiB    6.2%
 Bonds.jl                         1    27.0s    3.7%    284MiB    2.0%
 RichOutput.jl                    1    45.1s    6.1%   1.31GiB    9.5%
 React.jl                         1     116s   15.8%   2.91GiB   21.2%
 Dynamic.jl                       1    31.5s    4.3%    799MiB    5.7%
 MacroAnalysis.jl                 1    98.9s   13.4%    825MiB    5.9%
 Logging.jl                       1    15.1s    2.0%   52.8MiB    0.4%
 webserver.jl                     1    20.6s    2.8%   1.52GiB   11.1%
 Notebook.jl                      1    87.5s   11.9%    568MiB    4.0%
 Configuration.jl                 1    8.27s    1.1%    402MiB    2.9%
 ReloadFromFile.jl                1    4.92s    0.7%    100MiB    0.7%
 packages/PkgCompat.jl            1    398ms    0.1%   33.1MiB    0.2%
 ExpressionExplorer.jl            1    5.28s    0.7%    317MiB    2.3%
 MethodSignatures.jl              1    132ms    0.0%   15.7MiB    0.1%
 MoreAnalysis.jl                  1    925ms    0.1%   79.9MiB    0.6%
 Analysis.jl                      1   94.6ms    0.0%   4.12MiB    0.0%
 webserver_utils.jl               1    818ms    0.1%   43.1MiB    0.3%
 data structures.jl               1    713ms    0.1%   68.3MiB    0.5%
 DependencyCache.jl               1    355ms    0.0%   27.4MiB    0.2%
 Throttled.jl                     1    841ms    0.1%   2.14MiB    0.0%
 cell_disabling.jl                1    536ms    0.1%   26.9MiB    0.2%
 ───────────────────────────────────────────────────────────────────── 
```

The `compiletimes.jl` runs first and gives an estimate of how long compilation takes.

**Comment by rikhuijzer** [comment]
@fonsp Can you review this?

**Comment by fonsp** [comment]
I took the sessionactions precompile statements out, let's do that in a new PR (also so that we can use these timing to see the difference!!)

**Comment by fonsp** [comment]
Thanks!! Looks great! Seeing allocations seems very useful in CI

**Comment by fonsp** [comment]
precompile statements in https://github.com/fonsp/Pluto.jl/pull/1977

**Pull request merged**
