### PR TITLE
moved arraybuffer fix to polyfill

### PR DESCRIPTION
**Pull request by fonsp**

### CODE REVIEW

**Comment by fonsp** [comment]
@oem

**Comment by oem** [comment]
looks good (and works too).

**Comment by fonsp** [comment]
@oem Thanks so much! Are you interested in working on Pluto? 😊 The Julia part doesn't change much these days, it's mostly a JS project!

Have a look at:
https://github.com/fonsp/Pluto.jl/issues/111
https://github.com/fonsp/Pluto.jl/issues/235
https://github.com/fonsp/Pluto.jl/issues/13
and
https://www.notion.so/b26b9d46aa904cb0a8bd49e71e195e9d?v=b0b4efde8cc54481aae1478bcc0bfccc

Let's have a video call if you have some ideas!

**Comment by oem** [comment]
heya @fonsp, sorry for the delayed response - I am a bit pressed for time atm, but I would love to work on pluto. Let me have a look at the tickets when I find some time and I will ping you if I have any ideas :) 
And thank you for building pluto, I really enjoy using it!

**Comment by fonsp** [comment]
Sure thing! fonsvdplas@gmail.com

**Pull request merged**
