### PR TITLE
Ignore assignment to underscores

### PR DESCRIPTION
**Pull request by mcabbott**
It's common assign throw-away values to `_`; this changes ExpressionExplorer to ignore them:

Screenshot 2021-03-19 at 12 46 22

In Pluto right now, this example gives a multiple assignment error, since two cells appear to write to the same variable. But they don't really, since `_` cannot be read from.

~~(Not sure why tests seem to see a dependence on `_`, even though they correctly don't think it's being written to.)~~

### CODE REVIEW

**Comment by pankgeorg** [comment]
I understand correctly that this is the expected julia behaviour right?
image

Can you add a reference to the docs, if any, just for completeness?

**Comment by Pangoraw** [comment]
> (Not sure why tests seem to see a dependence on _, even though they correctly don't think it's being written to.)

To account for special cases like this:
```julia
x[a+b] = ... # will reference a, b and x, will assign to x
```
Pluto explores the left side of the assignment like any other expression. It then removes from the references any assignments, see the `setdiff` in `ExpressionExplorer.jl`:

https://github.com/fonsp/Pluto.jl/blob/a454b61a14e9116e3c7b04dc9bea70f41ed019ea/src/analysis/ExpressionExplorer.jl#L317

If `_` cannot store values between cells, perhaps it would be simpler to not consider them in the references as well.

**Comment by mcabbott** [comment]
Thanks, that's what I couldn't find. I think the last commit should remove them from being seen as references too. 

I'm not actually sure where this is documented, it's discussed e.g. [here](https://discourse.julialang.org/t/usage-rules-for-bare-underscores/28858).

**Review by fonsp — CHANGES_REQUESTED** [review]
>  I think the last commit should remove them from being seen as references too.

Can you add a test?

image

Can you extend this PR to any "all-underscore" variable name?

**Comment by mcabbott** [comment]
There are some tests, could expand? 

Didn't think of multiple underscores, but have now expanded it to handle these too.

**Comment by fonsp** [comment]
Can you add a test for this remark:

> I think the last commit should remove them from being seen as references too.

**Comment by mcabbott** [comment]
This is the change that went with that remark: 

Screenshot 2021-03-22 at 08 53 17

**Review by fonsp — APPROVED** [review]

**Comment by fonsp** [comment]
Thanks @mcabbott !

**Pull request merged**
