### PR TITLE
Test Julia 1.9

### PR DESCRIPTION
**Pull request by Pangoraw**
- Test 1.9
- Potential fix to #2427
    This seems to be a weird issue with splatting or `union!` but I
    could not manage to reproduce outside.

### CODE REVIEW

**Comment by fonsp** [comment]
The tests take 50% longer to run on 1.9 🤔 cc @rikhuijzer

**Comment by rikhuijzer** [comment]
> The tests take 50% longer to run on 1.9 thinking cc @rikhuijzer

Yes I'm very happy with Paul's work because now we can hopefully use the new package compilation better. I'm hope to find some time soon to switch `Pluto.jl` from `PrecompileSignatures.jl` to `SnoopPrecompile.jl`. That should probably reduce TTFX.

**Comment by greimel** [comment]
That's great! Do you plan to release this anytime soon?

**Comment by fonsp** [comment]
Yep! Rik is working on #2441 , we will release both PRs together probably. Just releasing this PR makes me worries about the 50% performance loss

**Comment by rikhuijzer** [comment]
> The tests take 50% longer to run on 1.9 thinking cc @rikhuijzer

Likely due to a bug in Julia-1.9.0-beta2 which was fixed in Julia-1.9.0-beta3. In beta2, `import Pluto` took 59 seconds while it takes only 2 seconds in beta3.

**Comment by pankgeorg** [comment]
> > The tests take 50% longer to run on 1.9 thinking cc @rikhuijzer
> 
> Likely due to a bug in Julia-1.9.0-beta2 which was fixed in Julia-1.9.0-beta3. In beta2, `import Pluto` took 59 seconds while it takes only 2 seconds in beta3.

For the first time, I get ~80 on master. Is this with a clean cache on `main`? (I noticed `julia` is smart enough to cache precompilations through branches)

**Comment by rikhuijzer** [comment]
> > > The tests take 50% longer to run on 1.9 thinking cc @rikhuijzer
> > 
> > 
> > Likely due to a bug in Julia-1.9.0-beta2 which was fixed in Julia-1.9.0-beta3. In beta2, `import Pluto` took 59 seconds while it takes only 2 seconds in beta3.
> 
> For the first time, I get ~80s on `main`. Is this with a clean cache on `main`? (I noticed `julia` is smart enough to cache precompilations through branches)

What do you do to get that time and which Julia version are you running?

**Comment by fonsp** [comment]
I think the number from @pankgeorg included precompilation (you get this when you run `import Pluto` directly after switching branches or Julia versions), which can take 80 seconds on Julia 1.9 😵‍💫

**Comment by pankgeorg** [comment]
Yes this is the precompilation time, without any cache.

**Comment by fonsp** [comment]
I have been discussing this @rikhuijzer , precompilation went from 15s to 60s (!) in Julia 1.9, and TTFX went from 30s to 20s. I'm a bit worried and I think we should open a Julia issue, Rik is mostly happy with the TTFX gains :)

60 seconds seems extremely long to me, that's 120 seconds on an older laptop. After seeing most other packages precompile in 3 seconds, people might assume that something is broken and restart Julia...

**Comment by greimel** [comment]
Right, but you already get the regression with the current release of Pluto on Julia 1.9 beta (in addition to Pluto bugs). Isn't releasing this already a strict improvement? The precompile time is orthogonal to the bug fixed here and can be fixed in a later release, can't it?

**Comment by fonsp** [comment]
Publishing a release is [more complex than it sounds](https://youtu.be/o_4EX4dPppA?t=144), but yes, a release is coming 👍

**Pull request merged**
