### PR TITLE
fix broken svg display

### PR DESCRIPTION
**Pull request by jveres**
The last update broke the svg display in cells. This PR fixes it and still uses the image tag to be able to right click save.

### CODE REVIEW

**Comment by fonsp** [comment]
Could you post an SVG file that's broken?

**Comment by fonsp** [comment]
It looks like this breaks all other image MIMEs by giving them all the svg MIME and base64 encoding already-encoded data?

**Comment by fonsp** [comment]
I realise that I never really tested this new function, but the idea was that svg image data does not need to be base64-encoded.

**Comment by jveres** [comment]
e.g. `using GR; inline("svg"); contourf(peaks())`

**Comment by fonsp** [comment]
Thanks, I'm having a look now

**Comment by jveres** [comment]
> It looks like this breaks all other image MIMEs by giving them all the svg MIME and base64 encoding already-encoded data?

Right, I totally overlooked it. Fixed in https://github.com/fonsp/Pluto.jl/pull/261

**Comment by jveres** [comment]
> I realise that I never really tested this new function, but the idea was that svg image data does not need to be base64-encoded. I'll experiment with it again.

Correct, can be with or without base64. The root cause was the missing encoding.

**Pull request closed without merging**
