### PR TITLE
🔌 Automatic reconnect

### PR DESCRIPTION
**Pull request by fonsp**

### CODE REVIEW

**Comment by fonsp** [comment]
@shashi

**Comment by fonsp** [comment]
I have updated the binder - try it out:

https://mybinder.org/v2/gh/fonsp/vscode-binder/master?urlpath=pluto

**Comment by fonsp** [comment]
Omg!!! I can get it to link to the file!! 

Put this in an iframe and we're done!

https://mybinder.org/v2/gh/fonsp/vscode-binder/master?urlpath=pluto/open?url=https%3A%2F%2Fraw.githubusercontent.com%2Fmitmath%2F18S191%2Fmaster%2Fhomework%2Fhomework1%2Fhw1.jl

**Comment by fonsp** [comment]
Still needs to be faster but i have some ideas

**Comment by fonsp** [comment]
holy moly

**Comment by fonsp** [comment]
#105

**Comment by fonsp** [comment]
#281 #280

**Comment by fonsp** [comment]
@lungben Maybe you can help me make the binder faster?

**Comment by fonsp** [comment]
@dralletje

**Comment by fonsp** [comment]
https://pluto-on-binder.glitch.me

**Comment by shashi** [comment]
So tell me can we put this on the website? :-p

What would be the problems?

So if say 10 people are looking at it, does it start 10 mybinders?

What about latency?

I tried the glitch link, looks awesome! it takes a while but it works!

**Comment by fonsp** [comment]
It's down to 40 seconds now! Try it again
20 seconds until the pluto main menu, 40 seconds until you can read the first notebook text (when opening a direct link)
We had a go with running PackageCompiler, but the binder build step did not like it so we're still not creating a custom sysimage. Ideally for the lectures, you would not only precompile Pluto but also all the dep packages, by running the notebook as a representative workload for PackageCompiler

1000 students will launch 1000 binders. Don't know if that's a problem. I'm guessing that they are used to getting traffic spikes from lectures and presentations.

Latency is a problem if you have poor internet - most UI actions have to make a round trip. But typing is offline

**Pull request merged**
