### PR TITLE
don't error when state contains Ptrs

### PR DESCRIPTION
**Pull request by aplavin**
eg warnings from depwarn()

### CODE REVIEW

**Comment by dralletje** [comment]
Do you have a quick example for how I can trigger the error you are fixing?

**Comment by aplavin** [comment]
Run any function that throws a depwarn, eg:
```
# ╔═╡ 0328b0ab-faf6-4c80-9d0e-bc06ed90f9bc
using LinearAlgebra

# ╔═╡ f5ecc5ca-7a2b-4c96-ad74-97e01e7803cf
BLAS.vendor()
```
Go back to the pluto notebooks list (index page) and try to open this notebook again (don't restart it). Pluto webinterface hangs with "Loading...", and the terminal shows
```
┌ Warning: Failed to write to WebSocket of xa3u8u 
│   exception =
│    no non-`AnyType` MsgPack mapping found for Ptr{Nothing}; please overload `msgpack_type` for this type.
...
```

**Comment by dralletje** [comment]
I see.
Ideally we don't transfer the `log.id` to the main process/the client at all.. (or we stringify it)
@Pangoraw we're only using it for ProgressLogging right now, right? You know if it safe to "just" `string(...)` it?

**Comment by Pangoraw** [comment]
oh interesting, I totally did not expect log ids to be custom objects. We can use `objectid(log.id) |> string` which gives a consistent hash for ProgressLogging if not serialisable ?

**Comment by fonsp** [comment]
Oh no! I closed by accident and now it says:

Schermafbeelding 2022-02-02 om 13 01 57

**Comment by fonsp** [comment]
Thanks for reporting this! Fixed in https://github.com/fonsp/Pluto.jl/commit/f094e02fe76b670a504a90320c4081c13632fc81

**Comment by aplavin** [comment]
Thanks for a more proper fix, seems to work fine!

**Pull request closed without merging**
