### PR TITLE
Page parameter `pluto_server_url` overrides default WebSocket address

### PR DESCRIPTION
**Pull request by ctrekker**
The Pluto.jl desktop app needs a way to tell Pluto explicitly where to find a Pluto.jl WebSocket server running, since frontend assets are served directly from the filesystem (a `file://` url). As far as I can tell, there was no way to do this already built into Pluto.jl, so this PR adds a page parameter to the editor and welcome screen which overrides the default websocket url behavior.

### CODE REVIEW

**Comment by fonsp** [comment]
Nice! Can you re-use the `pluto_server_url` for this? Right now the only purpose is to define where a featured notebook preview should make the `/open` request, but maybe this setting can also be used as the "where is the WS server" setting.

**Comment by ctrekker** [comment]
Adding websocket-related behavior for `pluto_server_url` will work, at least for PlutoDesktop! My only worry is that these changes may cause issues for binder. I'm not sure how to test these changes on binder without them being included in a release

**Comment by fonsp** [comment]
You can test binder by generating a test URL yourself, e.g.

http://localhost:1235/editor.html?statefile=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2FJuliaPluto%2Ffeatured%40v2%2Fbasic%2FInteractivity.plutostate&notebookfile=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2FJuliaPluto%2Ffeatured%40v2%2Fbasic%2FInteractivity.jl&disable_ui=true&binder_url=https%3A%2F%2Fmybinder.org%2Fv2%2Fgh%2Ffonsp%2Fpluto-on-binder%2Fv0.19.23

I'm testing it right now. Featured notebooks also still work 👍

**Review by fonsp — APPROVED** [review]
Binder still works 👍

**Pull request merged**
