### PR TITLE
Slightly tweak @htl intro in JS sample notebook

### PR DESCRIPTION
**Pull request by icweaver**
As a total noob to web programming, I thought these slight changes helped me follow the logical flow of the text a bit better. Pretty much whenever new topics are introduced, I like following the rule of thumb of just addressing it up front (e.g. with hyperlinks or whatever), and then calling back to it when it's mentioned for the second time.

No idea if that makes sense, but just thought I'd bring this up to see what folks thought!

### CODE REVIEW

**Comment by dralletje** [comment]
Damn I merged the previous pull request so this one now doesn't merge nicely..
Can you re-do this based on current main? 😅

**Comment by icweaver** [comment]
Oh yea, that is my b. Sorry about that, should be fixed now! (I hope)

**Comment by fonsp** [comment]
Thank you! I forgot to mention: we have to create and edit the sample notebooks in Julia 1.6, because of the manifest changes in 1.7. 

A manifest created in 1.6 has the widest compatibility across Julia verisons, although it's not a big deal if the manifest does not work, in that case Pluto will create a new one (but it takes a bit longer to load).

**Pull request merged**
