### PR TITLE
Sort autocomplete by showing lowercase first

### PR DESCRIPTION
**Pull request by iboss-ptk**
Resolve part of #302:
- lowercase first, then uppercase

### CODE REVIEW

**Comment by fonsp** [comment]
If it sorts in reverse, does it now give `z` before `a`?

**Comment by iboss-ptk** [comment]
@fonsp It is. Should we go like
- lowercase
- @stuffs (for macro)
- uppercase
- the rest
sorted alphabetically for each bucket instead?

**Comment by iboss-ptk** [comment]
@fonsp It is. Should we go like

lowercase
uppercase
the rest
sorted alphabetically for each bucket instead?

**Comment by fonsp** [comment]
Yep! Just a style comment: you can use a [stable sort algorithm](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability) like MergeSort, and sort by a function that just assigns categories:
```julia
heuristic(s::String) = if islowercase(firstchar(s))
	1
elseif isuppercase(firstchar(s)
	2
else
	3
end
```

**Comment by iboss-ptk** [comment]
@fonsp cool! I will look into that :D

**Pull request merged**
