### PR TITLE
Automatically generate SRI attributes in bundle

### PR DESCRIPTION
**Pull request by fonsp**
I forgot why I did this........ 😵‍💫  but might be useful for #1952 depending on how we solve that

### CODE REVIEW

**Comment by fonsp** [comment]
I really really tried to do this using a parcel plugin but it's "not possible"

**Comment by fonsp** [comment]
This script adds the `integrity` attribute, but not the `crossorigin` attribute. You can only use integrity on remote (jsdelivr) scripts if `crossorigin=anonymous`, so this caused the static html exports in 0.19.7 to break :(

I created a PR to fix this but it's "out of scope" https://gitlab.com/Abogical/posthtml-sri/-/merge_requests/5

**Comment by Abogical** [comment]
Hello @fonsp !

I might be a year late, but I just wanted to apologize if my tone was rude or arrogant in the discussion we had on that PR.

I like Julia's ecosystem, especially Pluto. so I was pleasantly surprised to see my package being used there. It might not mean much, but I appreciate it.  And thanks for your work on Pluto ❤️

**Comment by fonsp** [comment]
Hey @Abogical, thanks for your message!

It's very important to stick to your scope and be strict about it, sometimes that means disappointing users :) I think I was just surprised that it was out of scope, but no worries.

Have a good time with Pluto, and we are always looking for contributors who know JavaScript!

-fons

**Pull request merged**
