### PR TITLE
Hide UndefVarError if the upstream cell errored

### PR DESCRIPTION
**Pull request by HirumalPriyashan**
- Addresses https://github.com/fonsp/Pluto.jl/issues/1179

**Implementation details**
- check whether the current is erred due to a `UndefVarError`.
- find that undefined variable and check whether its due to an error in an upstream cell
- if the err is due to an err in upstream cell, replace the current cell output with upstream cell's erred output

**New behavior**
image

### CODE REVIEW

**Comment by fonsp** [comment]
Do you think that it is possible to implement this in https://github.com/fonsp/Pluto.jl/blob/main/frontend/components/ErrorMessage.js instead? And always be sure to give a (short) description to you PR: how is it implemented, maybe explain why you chose this implementation, and show screenshots/videos of the new behaviour.

**Comment by HirumalPriyashan** [comment]
@fonsp 

> Do you think that it is possible to implement this in https://github.com/fonsp/Pluto.jl/blob/main/frontend/components/ErrorMessage.js instead? 

I have taken this approach as we don't have access to cell result of errored upstream cell (`notebook.cell_results[upstream_cell_id]`) in `ErrorMessage.js`

But seems like we can get those values through `pluto_actions.get_notebook()` in `ErrorMessage.js`. Will check the possibility of that approach and update the PR.

> And always be sure to give a (short) description to you PR: how is it implemented, maybe explain why you chose this implementation, and show screenshots/videos of the new behaviour.

Updated the PR description.

**Comment by HirumalPriyashan** [comment]
@fonsp 

Updated the PR using https://github.com/fonsp/Pluto.jl/blob/main/frontend/components/ErrorMessage.js .
Since there is no point of showing upstream error body in the current cell, updated the msg with a new error msg.

**New behavior**
image

**Comment by fonsp** [comment]
Some ideas:
- Can you make it recursive? i.e. if you have three cells, `x = sqrt(-1)`, `y = x`, `z = y`, then the last two cells should show the redirect message instead of an undefvarerror.
- What happens when there are multiple upstream variables? E.g. `a = b = sqrt(-1)`, `a + b`.
- Can you insert a clickable link to the upstream variable(s)?
- Let's remove the stack trace

**Comment by HirumalPriyashan** [comment]
> * Can you make it recursive? i.e. if you have three cells, `x = sqrt(-1)`, `y = x`, `z = y`, then the last two cells should show the redirect message instead of an undefvarerror.
> * Let's remove the stack trace

At the moment, these two are already available with the changes. Please let me know if I did not understand it correctly. But I think we can point error in the third cell to `a` since the error is due to failure of computing of `a` not `b`.
image

> * What happens when there are multiple upstream variables? E.g. a = b = sqrt(-1), a + b.

Right now, it just displays the first upstream cell which identified as errored. But sure, we can update it for multiple variables.

> * Can you insert a clickable link to the upstream variable(s)?

Sounds cool, yes we can do that.

**Comment by HirumalPriyashan** [comment]
**New behavior**

*Added a clickable link for upstream variables*
*Notice for the fifth cell errors are produced for the root cause, since `c` is errored due to `a` and `b`.*

image

**Comment by fonsp** [comment]
This is great, thanks @HirumalPriyashan !!

I made some small changes, including:
- [`dd0a631` (#2057)](https://github.com/fonsp/Pluto.jl/pull/2057/commits/dd0a6314423b94021945d36bae4f52c442e7de7d): this is not really internal *state* (you don't want this value to persist across renders)
- [`1bb4aae` (#2057)](https://github.com/fonsp/Pluto.jl/pull/2057/commits/1bb4aae9be0f5b1c8c8f10951cfda2154cc52d30) this fixes [this issue](https://user-images.githubusercontent.com/6933510/169162054-d80fa7be-1ccf-4a4e-8f0b-97cc45e4fb0c.png), which could be confusing/frustrating in a large cell with multiple errors.

**Review by fonsp — APPROVED** [review]

**Comment by KronosTheLate** [comment]
I am late to the party, but want to give a huge appreciation for this fix <3

**Pull request merged**
