### PR TITLE
Move to backtick latex delimiting

### PR DESCRIPTION
**Pull request by jlewis91**
Per the very helpful tip in [this discourse thread](https://discourse.julialang.org/t/pluto-markdown-not-working/53433), it seems like there might be a lot to be gained and little to be lost by encouraging users to use backticks instead of dollar signs for latex snippets, so that dollar signs are reserved for (and more reliably parsed) in the case of `$(1+1)` style interpolation.

### CODE REVIEW

**Comment by fonsp** [comment]
Thanks! Did you check all sample notebooks?

**Comment by jlewis91** [comment]
@fonsp, yes, via regex, so I’m 98% sure I got everything. :)

**Comment by jlewis91** [comment]
@fonsp Can now in good faith say that I've reviewed all of the sample notebooks. Some of the diff updates are because I reran the notebooks in 0.14; let me know if you'd prefer I remove these commits.

**Comment by fonsp** [comment]
Yeah can you try to get smaller diffs?

**Comment by jlewis91** [comment]
@fonsp Ok, think we have a clean diff now. :)

**Pull request merged**
