### PR TITLE
implemented tests towards solving issue #177

### PR DESCRIPTION
**Pull request by karlwessel**
Implementation of the tests from [fons' comment](https://github.com/fonsp/Pluto.jl/issues/177#issuecomment-645039993) towards implementing issue #177 .

All of them pass and ideally should still pass when issue #177 is implemented.

### CODE REVIEW

**Comment by fonsp** [comment]
Why do they pass?

**Comment by karlwessel** [comment]
Because they actually are true positive cases of `multiple definitions of the same method` and Pluto currently detects every method with the same name as a case of `multiple definitions of the same method`.

So Plutos current tactic is to find all true positives by just finding all positives, including the false ones :).

**Review by karlwessel — COMMENTED** [review]
Why? When one of the definitions is deleted it is correct that there is no multiple definitions error anymore.

**Comment by fonsp** [comment]
Thanks @karlwessel !

I merged your branch into a development branch: [`ab13217` (#538)](https://github.com/fonsp/Pluto.jl/pull/538/commits/ab13217d8e090d39745ea8aed2b61833ef43ef61)

and your tests are now inside Pluto!

**Pull request closed without merging**
