### PR TITLE
PJL-631 translateY keyframe animation

### PR DESCRIPTION
**Pull request by pankgeorg**
This pull request addresses [Issue 631](https://github.com/fonsp/Pluto.jl/issues/631) about High CPU Load with CSS animations.

- Use a variable to define the logic of `--patternHeight: 22.62741699797px`
- Set overflow of traffic-light to hidden
- Use a pseudo-element to render background image. Height of pseudo-element is `100% + 2 * patternHeight`
- Move element with animation, over the course of 1 second to 1 `patternHeight` lower.

Note: in order to run the animation, a parent of the element must have the `--patternHeight` variable set. That is if the animation is to be used elsewhere (this change makes the animation really reusable, because it _can_ be used in different settings with different pattern heights).

Result: In my computer (Chrome / Firefox on Windows 10) the cpu load drops from 60-70% to around 20%.

Let me know of your thoughts,

Thanks,
Panagiotis

### CODE REVIEW

**Comment by fonsp** [comment]
@dhanak Could you try this out?

**Comment by dralletje** [comment]
This is PERFECT
Just for reference

Paints before:
image

Paints after:
image

**Comment by dhanak** [comment]
Wow, you guys are really quick! Kudos for the teamwork!

**Comment by Pocket-titan** [comment]
Real nice @pankgeorg 🔥

**Pull request merged**
