### PR TITLE
Shortcut for auto-indent in cells

### PR DESCRIPTION
**Pull request by pbouffard**
Uses CodeMirror `indentAuto` command on selection.

### CODE REVIEW

**Comment by fonsp** [comment]
Is this the same shortcut as VS Code?

**Comment by pbouffard** [comment]
Seems so on Mac and Windows, possibly not Linux: https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf

Actually I should say it's _close_ on Windows and Mac: https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf.. Ctrl+Alt+F (Windows) and Ctrl+Option+F (Mac) are actually "Format document" in VS Code while "Format selection" is a 2-step shortcut, Ctrl+K Ctrl+F. It think I saw in other threads that 2-step shortcuts were undesirable (and maybe impossible with CodeMirror?) and picked what I did.

Also, the reason to not just do "format document" (i.e. the whole cell) is that the the CodeMirror `indentAuto` command trashes any leading whitespace in multi-line strings which is not usually what you want.

**Comment by dralletje** [comment]
That's a pretty stupid auto-indent 😂 
Seems a bit counter productive to have a formatting shortcut that possibly changes the behaviour of your program, if you run it while you have the wrong line selected.
I'd rather see a good formatter so we can make it "Format cell" without any surprises.. Know of a better formatter by any chance?

**Comment by Pocket-titan** [comment]
We could use https://github.com/julia-vscode/DocumentFormat.jl from the `julia-vscode extension`?

**Comment by dralletje** [comment]
DocumentFormat, even though it also doesn't look perfect, seems like a way better option indeed

**Comment by pbouffard** [comment]
I had originally [suggested](https://github.com/fonsp/Pluto.jl/issues/586#issuecomment-713895178)  something similar but @fonsp [wants to](https://github.com/fonsp/Pluto.jl/issues/586#issuecomment-714348668) stick with a more basic auto-indent for now.

AFAIK the only issue with the current PR is how indentation in multi-line strings can get affected; IMHO code depending on leading whitespace in such strings is probably pretty brittle to begin with.

Getting DocumentFormat.jl integrated sounds like a more involved task and I'd be interested in helping but probably would need some assistance; so far I've just been nibbling at some of the easier items on the front-end side of Pluto.

**Comment by fonsp** [comment]
We will not implement a formatter right now. 

> possibly changes the behaviour of your program, if you run it while you have the wrong line selected.

In that case, the shortcut should not auto-indent your selection, it should auto-indent the entire cell. Does that solve the problem?

**Comment by dralletje** [comment]
How is Codemirror autoIndent not "implementing a formatter", but using a different package is? You make no sense

**Comment by fonsp** [comment]
(We decided to come back to this later)

**Pull request closed without merging**
