### PR TITLE
Add Github /raw link support

### PR DESCRIPTION
**Pull request by musabkilic**
Explained here: #492

### CODE REVIEW

**Comment by zmoon** [comment]
Seems like it would be safer to replace `"/raw/"`? Because if it is a `/blob` link and the filename starts with `raw` that would mess it up.

**Comment by musabkilic** [comment]
Yes, I get your concern and I was just thinking about the same thing. Another thing to mention is that if the author or the repository name starts with "blob", current code replaces that part. This might sound unlikely but it can cause problems in the future.

I think the best/safest way to handle this is to *not* change github.com to raw.githubusercontent.com. Instead, adding "?raw=true" query string to URL returns the corresponding raw.githubusercontent.com page, i.e we can let Github redirect the raw file link.

Example:
https://github.com/fonsp/Pluto.jl/blob/master/sample/Basic.jl => https://github.com/fonsp/Pluto.jl/blob/master/sample/Basic.jl?raw=true

It's also easy to implement with just adding `u.searchParams.set("raw", true)` and removing the "replace /blob with this github with that" part. If @fonsp is happy with this approach, I can update the code.

**Comment by zmoon** [comment]
That's cool! Then any of the GitHub link types can be used, no `pathname` modification necessary.

**Comment by fonsp** [comment]
There's a reason why I didn't use that, but I forgot what it was 😬 Let me think...

**Comment by musabkilic** [comment]
https://github.com/fonsp/Pluto.jl/commit/b26b0f1df4e131f9f2b285c622048f72b22b47f9#diff-d5648022db67f8ce30e167edf519aa1eR47

https://github.com/fonsp/Pluto.jl/commit/9fdc353e487ce097481b86edb5745a4ca4597fce#diff-d5648022db67f8ce30e167edf519aa1e

These might refresh some memories. Maybe setting the search/query part(not adding raw=true, just replacing all the query part) caused some problems.

**Comment by fonsp** [comment]
Haha thanks, now I remember:

I changed it here: https://glitch.com/edit/#!/pluto-on-binder

because I had an escaping issue with the `?`, but I later found that the issue is solved by URL encoding twice :)

Let me try...

**Comment by fonsp** [comment]
Resolves #492

**Pull request merged**
