### PR TITLE
ANSI colored output in captured stdout

### PR DESCRIPTION
**Pull request by HirumalPriyashan**
- addresses https://github.com/fonsp/Pluto.jl/issues/2144

image

### CODE REVIEW

**Comment by fonsp** [comment]
Nice! You can set `:color => true` here https://github.com/fonsp/Pluto.jl/blob/d05bccc6dd60434dfae15756a3a5fd25bd800444/src/runner/PlutoRunner.jl#L923 to tell Julia packages that they can write to `stdout` in color. 

Can you also make a screenshot of Crayons.jl?

**Comment by HirumalPriyashan** [comment]
image

**Comment by fonsp** [comment]
Nice! Looks like we were using AnsiUp incorrectly, which is why the second cell in your screenshot was shown in red (this state was remaining after rendering the first cell). I added a commit to fix that

**Comment by fonsp** [comment]
image

Maybe #2088 next? :)

**Comment by HirumalPriyashan** [comment]
@fonsp 
Let's update ansi_up version as well.
https://github.com/fonsp/Pluto.jl/blob/d1ebadef5689dbacf158e347d342def237e39c8c/frontend/editor.html#L29
@v5.1.0 supports underline, italic as well.

**Comment by icweaver** [comment]
oh heck this is cool!

**Comment by fonsp** [comment]
Oooh awesome, lets do that!

**Comment by rafaqz** [comment]
Is this meant to work with regular `show` text/plain output now? I notice say DimensionalData.jl output is coloured in the REPL but single color in Pluto.jl, losing a lot of useful information.

**Pull request merged**
