### PR TITLE
Better File Note Found Page

### PR DESCRIPTION
**Pull request by TheCedarPrince**
So far, this is what I have been working on (started from #77):

image

I am thinking the error page can be very similar to the original welcome page but can also display the error message. Working on adding the recent files part as well. 

Running into a couple difficulties on how to do this however. @fonsp how do I:

1. Use an `HTTP.Response(404)` to redirect the user to another page? I tried looking at the documentation but was confused by how to do this.

2. Do I want to pipe an error to this page from the back-end or do I want to explicitly say, when triggering a 404 error, "file not found" essentially?

Thanks!

### CODE REVIEW

**Comment by fonsp** [comment]
1. The _page response_ is not a 404 but a 200 (the default) - trying to view `http://localhost:1234/some_unknown_address` would be a 404. 
2. It has to be the Julia error - file not found is not the only possible error.

**Comment by fonsp** [comment]
Also, it looks like this is the same branch as your previous PR - can you delete this one and start from a clean fork? Or does that not make sense

**Comment by TheCedarPrince** [comment]
Yup, this should be on a separate branch. Do you mind deleting this PR while I set-up a new PR with a new branch?

**Comment by fonsp** [comment]
Try to fork off the latest version of the master branch from `fonsp/Pluto` (I don't know how git is hard)

**Pull request closed without merging**
