### PR TITLE
Highlight selected cell & minor UI tweaks

### PR DESCRIPTION
**Pull request by marius311**
Hi, I decided to mess with some things and get acquainted with the code by trying to smooth over some UI things which I thought were sharp edges as well as adding some simple missing stuff. For now I put everything in one PR here but happy to discuss individual changes and/or take them out. Summary:

1. Highlight selected cell. I often lose track of where in the code I am, this helped. 

selected_cell

2. Remove queued trafficlight animation. The recent work in https://github.com/fonsp/Pluto.jl/pull/349 great, but I think has just a few minor issues. First, I think animating the queued trafficlight is problematic because 1) its visually disorienting to have that many things moving on screen, especially at two different speeds 2) if the animation represents computation, it doesn't make logical sense that the queued cell is animating at all, since its not running yet and 3) because of the way the CSS animation works, there's often a visually jarring "jump" when switching from the slow speed to the fast speed since the fast speed always starts from an offset of zero. For these reasons, I took it out, but kept the repeating gradient on the queued cells, which I think nicely indicates the cells are about to run but currently are not running. I also removed the tiny differences in gradient colors because too many subtly different colors on-screen feels messy. End product: 

queued_cell

(I couldn't figure out how to get rid of the small flash after running is finished which sometimes happens, maybe this is just a CSS deficiency)

3. I removed linewrap, which no code editor that I know of has on by default. 

4. I made the cursor wider (same width as Jupyter's cursor on my screen fwiw), as Pluto's was really thin and I kept losing track of it. Would be good to double check this looks OK on other resolutions too. 

I did find all of these things improved the overall feel for me, but again, happy to discuss. Thanks!

### CODE REVIEW

**Comment by fonsp** [comment]
Very nice, thanks a lot!

The only thing is 3. - I've already thought hard about line overflows and decided upon the current design: line wrap with small dots before lines to indicate it. I don't want the cell editor to be scrollable content - this makes Pluto feel 'less robust'. If you want, you can open a separate PR about it, but I'd rather let this wait for #2

**Comment by fonsp** [comment]
I'll look into the trafficlight flicker again sometime

**Comment by marius311** [comment]
Great, glad you like it! Reverted 3, that sounds fair. I can imagine at some point in the future it'd be customizable which would be nice too.

**Comment by fonsp** [comment]
I tried it out and I have some comments:

### 2

Queued cells _should_ have a slowly moving traffic light. Right now, when you open a large notebook and the running cell is too far down to see, it just feels like the notebook has crashed. You're right that "moving" means that the cell means "running", but in web UI it often also means "things are not broken, give it a second". Progress bars create a more friendly experience: https://en.wikipedia.org/wiki/Progress_bar#Perception

The original PR #349 had a larger difference in animation speeds - let's try that again.

(I can live with the rotation jump when the animation speed changes.)

### 1

We should fix the positioning for small displays:
image

The 👁 clips with the window edge.

Also: instead of the focus bar being a darker color, maybe we can use the same color as the traffic light? Then the focused cell just has a traffic light that's twice as wide.

**Comment by marius311** [comment]
> Queued cells should have a slowly moving traffic light... it just feels like the notebook has crashed. 

Yea, I can see that. My only comment would be it seems cleaner to do slower speed or dimmed color for queued cells, but not both, mainly because of the too many subtle differences things. Between those two, I think I do prefer the slower speed. 

> Then the focused cell just has a traffic light that's twice as wide.

You're right, I think I broke my own "too many subtly different colors" thing here actually. 

> The eye clips with the window edge.

Good catch, I can try and fix that.

**Comment by fonsp** [comment]
Yeah thanks for pointing out that we don't need to add another color!

About the window edge - we can increase the margin on the left, but do so carefully - this is valuable screen space! Maybe we can squeeze the 👁 a little tighter?

**Comment by shashankp** [comment]
> > Queued cells should have a slowly moving traffic light... it just feels like the notebook has crashed.
> 
> Yea, I can see that. My only comment would be it seems cleaner to do slower speed or dimmed color for queued cells, but not both, mainly because of the too many subtle differences thing. Between those two, I think I do prefer the slower speed.
> 
> > Then the focused cell just has a traffic light that's twice as wide.
> 
> You're right, I think I broke my own "too many subtly different colors" thing here actually.
> 
> > The eye clips with the window edge.
> 
> Good catch, I can try and fix that.

thank you for the inputs 
This needed some direction & feedback to see which animation works best.

**Comment by fonsp** [comment]
Ping me when you're done!

**Comment by marius311** [comment]
After some more thought and testing, I don't think the two speeds are that good. The goal should be that when quickly glancing at the screen, you can easily identify what's running and what's queued, and trying to identify two different speeds in the end I don't think works. Instead, I came up with this:

queued_cell

I also tweaked the colors so the error-red matches the percieved alpha of the gray (red was really bright before), and such that the hatches always contain one color that matches the cell/selection highlight color so selecting things while they're running/queued still looks good. Ready to review from my end.

**Comment by fonsp** [comment]
This looks very very nice :)

**Comment by fonsp** [comment]
(I squashed the eyeball a little to make the left page margin smaller, and made it jump left when the cell is in focus.)

**Comment by fonsp** [comment]
Yayo thanks so much for your tasteful PR!

**Comment by marius311** [comment]
Great, thanks for the comments, they definitely improved the initial attempt! 

> (I squashed the eyeball a little to make the left page margin smaller, and made it jump left when the cell is in focus.)

FWIW I will say I don't think I like this. Every time you click a cell to select it, the little eyeball appears then immediately moves, and kind of draws your eye away unnecessarily. I'd say its worth the 4px to remove the distraction. I'll leave it up to you though!

**Comment by fonsp** [comment]
You’re right, and I’m not stuck to the current thing

Let’s leave it for a little while and fix it later? Also I’m still not sure how relevant the 200px wide screen layout is

**Pull request merged**
