### PR TITLE
Disable "Open" button on main menu when nothing is typed

### PR DESCRIPTION
**Pull request by HirumalPriyashan**
## Resolves
- https://github.com/fonsp/Pluto.jl/issues/1013

## Approach taken

- Set disabled property for `Open` button at start
- Add an id to `Open` button
- Set an event handler for input event to editor state and enable-disable the button

### CODE REVIEW

**Comment by fonsp** [comment]
Awesome! Can you use react to set the disabled state (`useState`) instead of modifying DOM directly? Take a look at https://reactjs.org/docs/hooks-intro.html

I think that you also don't need the `setTimeout`, but if you do, be sure to add a comment in code explaining why

**Comment by HirumalPriyashan** [comment]
Thanks for the feedback, made the suggested changes with `51cc7c3`.

> I think that you also don't need the setTimeout, but if you do, be sure to add a comment in code explaining why

Added `setTimeout` here as a workaround for unexpected behavior of `setState`, added a comment in code as well.

**Comment by HirumalPriyashan** [comment]
> What happens if you remove setTimeout? You probably don't need it anymore now that you rewrote it to use react state

There is a delay in update of state, sometimes it updates the state at the second or third input change

**Comment by fonsp** [comment]
Can you make a video?

**Comment by HirumalPriyashan** [comment]
sure,

without setTimeout

https://user-images.githubusercontent.com/57571152/161557807-127cb297-76b4-4c07-9b76-9cbc7d1ba510.mp4

with setTimeout

https://user-images.githubusercontent.com/57571152/161557936-1e9dbc00-a72d-476f-be68-6e64350b1c7d.mp4

**Comment by HirumalPriyashan** [comment]
Thanks, I will look into that and update the PR.

**Comment by HirumalPriyashan** [comment]
@fonsp updated the PR with a _codemirror compartment_

**Comment by fonsp** [comment]
Thanks! Can you run the VS Code formatter? This should happen automatically if you save the file in VS Code: https://github.com/fonsp/Pluto.jl/tree/main/.vscode

**Comment by HirumalPriyashan** [comment]
@fonsp I am using VS Code and formatting happens automatically when I save files, But  it doesn't seem to do any formatting to the current code.

**Comment by fonsp** [comment]
Be sure to install the "workspace recommended extensions", type `@recommended ` in the extensions search bar, and then click install:

Schermafbeelding 2022-04-20 om 14 16 11

**Comment by HirumalPriyashan** [comment]
Yes, I got them installed and been using them for a while now.
Still I have no idea why they didn't work here.

image

**Pull request merged**
