### PR TITLE
Fix svg display in cells

### PR DESCRIPTION
**Pull request by jveres**
Fixed svg display.

Screenshot 2020-08-06 at 21 59 16

### CODE REVIEW

**Comment by jveres** [comment]
Slightly better attempt for the same issue: https://github.com/fonsp/Pluto.jl/pull/260

**Comment by fonsp** [comment]
@JuliaRegistrator register()

**Comment by fonsp** [comment]
😢

**Comment by fonsp** [comment]
Thanks again @jveres !

**Pull request merged**
