### PR TITLE
Static preview, live Binder in the background

### PR DESCRIPTION
**Pull request by fonsp**
Schermafbeelding 2020-12-29 om 17 53 46

# A minimal demo of a static notebook transitioning to a live binder session

You can already run Pluto notebooks on binder, but the load times are too long without anything too look at. _You would not use this to write **interactive articles** on the web._ So we're still not revolutionizing scientific publishing! Oops!

The solution: 

> **Show a static preview of the notebook, and start a binder session in the background.**

## Demo link:

https://pluto-binder-static-to-live-1.netlify.app/editor.html?notebookfile=https%3A%2F%2Fmkhj.fra1.cdn.digitaloceanspaces.com%2Fsample%2520Tower%2520of%2520Hanoi%252016.jl&statefile=https%3A%2F%2Fmkhj.fra1.cdn.digitaloceanspaces.com%2Fsample%2520Tower%2520of%2520Hanoi%252016.jl.plutostate&binder_url=https%3A%2F%2Fmybinder.org%2Fbuild%2Fgh%2Ffonsp%2Fpluto-on-binder%2Fstatic-to-live-1

https://user-images.githubusercontent.com/6933510/103298204-1fda8b80-49fa-11eb-8cfb-a4d7ef28d1ee.mov

---

## How it works
We host the Pluto editor online on a CDN (i.e. we just host the `/frontend` folder):
https://jovial-newton-a0c386.netlify.app/
with the editor at:
https://jovial-newton-a0c386.netlify.app/editor.html

We host with a snapshot of the (React) state of the notebook: 
https://mkhj.fra1.cdn.digitaloceanspaces.com/sample%20Tower%20of%20Hanoi%2016.jl.plutostate
and the notebook file itself:
https://mkhj.fra1.cdn.digitaloceanspaces.com/sample%20Tower%20of%20Hanoi%2016.jl

These two URLs are passed to the editor as URL parameters. When the editor launhces with these url parameters, it downloads the state object and applies it locally, and displays a binder button.

A Binder session can be requested headless (in the background) using a special endpoint, `/build` instead of `/v2`. This is used by https://github.com/executablebooks/thebe

## Code

The important edits are on the Pluto side (this PR), with matching changes to our binder'ed repository:
https://github.com/fonsp/pluto-on-binder/pull/8

# Description of changes

Code to request a binder in the background, based on https://github.com/executablebooks/thebe
- Binder.js -- modified and stripped down code from thebe
- Editor.js -- if the right parameters are set, then dont connect to the WS immediately, but load the global state from a URL
- Editor.js -- handle binder connection phases

Some changes to allow an export script to generate a version of `editor.html` with CDNified resources (`http://cdn.jsdelivr.net/gh/fonsp/Pluto.jl@0.13.0/frontend/editor.css` instead of `./editor.css`) and a baked base64-encoded state object.
- editor.html -- `href="./` urls for easy string detection; HTML comment where JS can be inserted
- Editor.js -- a new unified parameter object that takes things from either `window.pluto_someproperty` or a `&someproperty=` url parameter
- Made serviceworker a single file 

CSS changes:
- editor.css -- a cool new binder button and loading bar like the video above
- editor.css -- allow the frontend to hide all UI (for blogs) by adding a class to `body` and by changing the `media` attribute of the `hide-ui.css` import from `print` to `all`

Some changes to allow the Pluto server to run fully on CORS requests if security is disabled:
- WebServer.jl -- allow random access to websocket when security is disabled
- Static.jl -- CORS header & a new `POST /open` endpoint to get the created notebook ID as a response, instead of a redirect to `/edit?id=<new id>`, since redirects don't CORS nicely

### CODE REVIEW

**Comment by fonsp** [comment]
@Ellipse0934 @mbauman I merged this and #988 into Pluto and released as 0.14.1! Normal users won't see the effects, but it means that 'vanilla' Pluto now has this functionality built in.

I also updated the popup box in the top right from a single binder button (like in the demo video of this PR) to the two-click button we used on https://computationalthinking.mit.edu/.

This should make it easier to edit and add options like the juliahub button!

**Comment by OvidiusCicero** [comment]
Pointer how to actually generate an HTML file programmatically as in https://github.com/fonsp/Pluto.jl/issues/899?

**Comment by Ellipse0934** [comment]
@OvidiusCicero You mean something like 
```julia
import Pluto
s = Pluto.ServerSession();
nb = Pluto.SessionActions.open(s, "./notebook.jl"; run_async=false)
html_contents = Pluto.generate_html(nb)
write("./notebook.html", html_contents)
```
?

**Comment by OvidiusCicero** [comment]
exactly thank you!

Is there a way to spawn this from a running Pluto session, maybe without the time intensive line

~~~
nb = Pluto.SessionActions.open(s, "./notebook.jl"; run_async=false)
~~~

?

**Comment by fonsp** [comment]
You can use the export button in the top right

**Comment by Ellipse0934** [comment]
@OvidiusCicero Maybe you want to use `@task` to decouple it and have it run independently while you work on other stuff.

**Comment by OvidiusCicero** [comment]
@fonsp  I want to trigger the export button programmatically

@Ellipse0934 i guess that works

**Comment by fonsp** [comment]
You can also right click the export button to get the link and do some hacking with the `download` function. `@__FILE__` can give you the notebook ID.

**Comment by OvidiusCicero** [comment]
grafik

@fonsp this looks like an approachable idea but `@__FILE__` neither returns the notebook id nor is the id part returned by it constant at all for me :(

**Comment by fonsp** [comment]
Ah oops, that is the cell id. Sorry!

**Comment by fonsp** [comment]
@OvidiusCicero https://github.com/fonsp/Pluto.jl/commit/72cfac410018e24852ed9e45b1f433d9897e9627

**Comment by OvidiusCicero** [comment]
@fonsp thanks, sorry I was distracted the last weeks

I can indeed get the ID of the notebook by `uuid = PlutoRunner.notebook_id[]|>string` but when I try `Downloads.download("http://localhost:1234/notebookexport?id=$uuid"` in Julia I get 

~~~
ERROR: HTTP/1.1 403 Forbidden while requesting http://localhost:1234/notebookexport?id=dec4a93e-ac3a-11eb-1117-775dcefcc761
~~~

when I open the link in the browser I seemingly get the HTML

> If you can convince me why this feature would be useful I can think about it more :)

I use the generated static HTML pages (okay, they're not so much static) from Pluto as reports to present results (like sending them around) and features like this would make keeping the HTML in sync with the actual notebook much easier

**Comment by fonsp** [comment]
Ah that's because the Pluto server is behind authentication. (You could disable authentication.)

Another idea is to fork Pluto and implement this directly. You could look for the places where we call `save_notebook`, and also save the export there.

**Comment by OvidiusCicero** [comment]
how are the authentications turned off? I found`require_secret_for_access= false)` but to no avail?

This and other stuff like `notebook="…"` or the TOCs seem to not be documented anywhere, would writing mini documentation for this somewhere (like the Wiki) be appreciated?

I'll also look into forking Pluto for this some time, this seems to be the cleanest way, but it will take time

**Comment by fonsp** [comment]
@OvidiusCicero It would be great if you could figure out a way to get those things into the docstring for `Pluto.Configuration`, ideally without duplicates. Then we can link to https://juliahub.com/docs/Pluto/OJqMt/0.14.5/autodocs/ if we want it online

**Pull request merged**
