### PR TITLE
Allow JS state (`this`) inside DivElement

### PR DESCRIPTION
**Pull request by fonsp**
cc @ghaetinger

### CODE REVIEW

**Comment by dralletje** [comment]
Smart!

**Comment by fonsp** [comment]
Maybe we should solve script ID before merging this..

**Comment by ghaetinger** [comment]
I've just tested this out using D3, which requires `this` to be persisted on updates. Here's how it works:

Using this PR:

https://user-images.githubusercontent.com/23220288/160865679-0ef9b119-3396-4b5d-b52b-2011718894cc.mp4

Without this PR:

https://user-images.githubusercontent.com/23220288/160866035-da0bdab7-dadd-4966-94cb-cab3793b22af.mp4

The animation looks really cool and it's completely removed without this 😢

**Comment by fonsp** [comment]
Thanks for testing!!

**Pull request merged**
