### PR TITLE
Shortcut to Duplicate a line

### PR DESCRIPTION
**Pull request by pbouffard**
Trying again.. 😅 Was difficult to find an unused shortcut, maybe worsened by (possibly mistaken here) not being able to use Ctrl for keybindings on Mac as they all get converted to Cmd. I don't have a Windows machine so I'm not sure if what I chose, which is Ctrl+Alt+Down, is available on PC.

image

Oct-21-2020 15-44-56

### CODE REVIEW

**Comment by fonsp** [comment]
Can you use the same shortcut as VS Code? I'm sure its not Ctrl+Alt+Down, because that flips the screen upside down on windows 🙃

**Review by fonsp — CHANGES_REQUESTED** [review]
Can you use the same shortcut as VS Code?

**Comment by pbouffard** [comment]
> Can you use the same shortcut as VS Code?

That is the Windows & Mac shortcut; it doesn't look like there is a default keybinding in Linux: https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf

**Comment by dralletje** [comment]
Copying line is shift-alt-up or shift-alt-down on both platforms, no?

**Comment by dralletje** [comment]
Also can you not do the `mac_or_pc_join` thing? We don't have to feel this Mac native, as long as people understand it and it works :P

**Comment by pbouffard** [comment]
> Also can you not do the `mac_or_pc_join` thing? We don't have to feel this Mac native, as long as people understand it and it works :P

I don't feel super strongly about it, just thought it might be nice. @fonsp what's your opinion?

**Comment by fonsp** [comment]
I will clean this up and merge

**Comment by dralletje** [comment]
Turns out, we have this now!

**Pull request closed without merging**
