### PR TITLE
Set keyboard shortcuts for adding a cell below or above selected cell

### PR DESCRIPTION
**Pull request by dgsob**
The default keys for this in Jupyter's command mode are "A" and "B" for cells above and below. Here I set it to be Alt+A and Alt+B (as in #65 the shortcut is not specified).

btw before/after - above/below is a little unfortunate

### CODE REVIEW

**Comment by fonsp** [comment]
What are the keyboard shortcuts for VS Code? We try to match the VS Code shortcuts, not necessarily Jupyter.

**Comment by damiansobecki** [comment]
> We try to match the VS Code shortcuts, not necessarily Jupyter.

I know but adding cells seems to be notebook specific action, I'm not aware of any VS Code notebooks.
Do you mean this? https://code.visualstudio.com/docs/datascience/jupyter-notebooks 
If so, the shortcuts are the same as in Jupyter's notebook. If this is not what you meant, sorry, I'm not familiar with VS Code.

**Comment by fonsp** [comment]
Exactly! VS Code has a notebook UI, the shortcuts are different.

**Comment by damiansobecki** [comment]
OK, nice. I meant this two specific shortcuts: "When a code cell is in command mode, the A key can be used to add a cell above and the B can be used to add a cell below the selected cell." That's from their doc I linked.

**Comment by xgdgsc** [comment]
From a previous jupyterlab user this is the first thing you would notice when switching to Pluto. Is there anything blocking this?

**Comment by dralletje** [comment]
VSCode uses <kbd>ctrl</kbd>+<kbd>;</kbd> <kbd>A</kbd> and <kbd>ctrl</kbd>+<kbd>;</kbd> <kbd>B</kbd>.
I guess they use <kbd>ctrl</kbd>+<kbd>;</kbd> as a "enter command mode" thingy.

**Comment by fonsp** [comment]
Right, and we don't want to have a "command mode" or "cell mode" for Pluto shortcuts. @dralletje is working on a way to create new cells with keyboard interactions only, by treating 3 newlines as a cell break. I think we should go with that instead!

**Pull request closed without merging**
