### PR TITLE
use javascript modules

### PR DESCRIPTION
**Pull request by dralletje**
Instead of using `window` to store all shared variables globally, use the es6 module system (natively supported in Chrome and firefox).
This doesn't make it magically clean, but it does allow for a more manageable javascript file structure.

For now I let all the files in place, but made as much as possible use of imports still

### CODE REVIEW

**Comment by dralletje** [comment]
Also please squash this 😁

**Comment by dralletje** [comment]
(Next to merge there is a dropdown where you can select "Squash and merge" to make this all one commit)

**Comment by fonsp** [comment]
Yay! I will look at it soon 👀

Does it work on safari?

**Comment by dralletje** [comment]
Yes

**Pull request merged**
