### PR TITLE
Add support for custom name in `@progress` (ProgressLogging.jl)

### PR DESCRIPTION
**Pull request by disberd**
This PR adds support for the visualization of custom names of progress bars created with `@progress` from ProgressLogging.

I also added a small sync icon to the logs of ProgressLogging as there was no icon at the moment.

## Before this PR
image

## After the PR:
image

### CODE REVIEW

**Comment by disberd** [comment]
@fonsp
We could also defaults to the name `Progress` in case no name was provided as done in the REPL when using TerminalLoggers.jl
image

I fine with either option, as the important part is to have the name displayed when it's actually provided in my opinion

**Comment by fonsp** [comment]
Nice! I didn't know about names but thats a very useful feature!

I'm not sure about the sync icon, I feel like it's not necessary because a progress bar is familiar. Or do you think this needs to be communicated better?

**Comment by disberd** [comment]
I just thought it felt strange not to have an icon when every other log had one, but I don't have a very strong opinion on this so we can also just ditch it

**Review by fonsp — APPROVED** [review]
Okay! Let's remove the icon.

The rest looks good! Two tweaks you can make:
- remove the console log
- use the CSS `:empty` pseudo-class instead of calculating it yourself

**Comment by disberd** [comment]
Thanks, did not know about the `:empty` selector, definitely better.

I removed the icon and applied the suggested changes, with this visual result:
image

**Comment by fonsp** [comment]
Thanks so much! Sorry, my holiday got inbetween 🙈

**Pull request merged**
