### PR TITLE
invalidate expanded exprs when dependent macros gets removed

### LINKED ISSUE #1753: Renaming a macro does not cause dependent cells to error
When renaming a macro in one cell that is referenced in other cells the dependent cells do not error as happens when doing the same for a method definition.

Prior to renaming:

image

After renaming and evaluating the first cell:

image

### PR DESCRIPTION
**Pull request by Pangoraw**
Fixes #1753.

### CODE REVIEW

**Comment by dralletje** [comment]
Nice

**Comment by fonsp** [comment]
Looks good! Nice to make 'invalidated cells' explicit. I didn't look at the PR carefully but I'll note that we already have this for frontend JS, stored here:

https://github.com/fonsp/Pluto.jl/blob/f881a6f113d1c9c20fecead071e05cb31e938cc8/src/notebook/Cell.jl#L12-L13

maybe it makes sense to unify the two?

**Review by fonsp — APPROVED** [review]

**Comment by fonsp** [comment]
@Pangoraw

**Comment by fonsp** [comment]
@Pangoraw can you close this or write a TODO list?

**Comment by Pangoraw** [comment]
I looked into removing `forced_expr_id` altogether but this moved a lot of logic to plutorunner so let's go with this instead!

is the `deletion_hook` in `update_run!` considered public API?

**Comment by fonsp** [comment]
> is the deletion_hook in update_run! considered public API?

What do you mean? Outside of our own code, I would say no, I think `update_run!` also isn't...

**Comment by Pangoraw** [comment]
> I think update_run! also isn't

Oh yeah! i have been confused because the tests are full of `update_run!` :see_no_evil:

**Comment by fonsp** [comment]
Cool! So good to merge?

**Comment by Pangoraw** [comment]
Let's go with this!

**Pull request merged**
