### PR TITLE
minor fix: Tables integration caused method ambiguation for Union{}[]

### PR DESCRIPTION
**Pull request by 16bitmood**

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
Fixes #1815 hopefully. Thanks @16bitmood!

**Comment by fonsp** [comment]
Awesome! Can we add a test here: https://github.com/fonsp/Pluto.jl/blob/111960219770272ff8c1a700f1f894bf50348db9/test/RichOutput.jl#L201 ?

**Comment by 16bitmood** [comment]
Hi,
I've added a few tests looking at the example ones. Let me know if there's anything else to add.

**Comment by fonsp** [comment]
Awesome, thank you for your contribution! Maybe you can also fix https://github.com/fonsp/Pluto.jl/issues/1385 ?

**Comment by 16bitmood** [comment]
Np :D
I will work on that.

**Pull request merged**
