### PR TITLE
No more wrapping `text/latex` with `\text{}`

### PR DESCRIPTION
**Pull request by zmoon**
Essentially reverts #381, which definitely seems to have caused more issues (breaking display of complex equation blocks for various packages, etc.) than it solved (fixing display for `LaTeXString`s with mixed text/math). Much discussion in #488.

I opened an issue at LaTeXStrings (https://github.com/stevengj/LaTeXStrings.jl/issues/50). Else, users can override the display for `LaTeXStrings` if they want like suggested [here](https://github.com/fonsp/Pluto.jl/issues/488#issuecomment-841655163)/[here](https://github.com/fonsp/Pluto.jl/issues/488#issuecomment-841687837), e.g. something like
```julia
Base.show(io::IO, ::MIME"text/html", s::LaTeXString) = 
    print(io, Markdown.LaTeX("\\text{$(s.s)}"))
```
seems to work ok. Or
```julia
function Base.show(io::IO, ::MIME"text/html", s::LaTeXString)
    texed = repr(MIME"text/latex"(), s)
    html(io, Markdown.LaTeX("\\text{$texed}"))
end
```

### CODE REVIEW

**Comment by fonsp** [comment]
Thanks! Is this PR still a draft? Can you add a TODO list?

**Comment by zmoon** [comment]
Hi @fonsp. I guess I wanted to wait a bit for LaTeXStrings to see if they respond. Also wondering, is it in the scope of Pluto to include this special case for LaTeXStrings within the Pluto codebase? If no, then I wouldn't necessarily add anything else to this PR unless you have something in mind.

Not in the scope of this PR, but what about some parsing of `text/latex` in order to split text and math? Jupyter seems to do this. For example, in JupyterLab:
image
:point_up: The text part is rendered as normal HTML text, only the math part is passed to MathJax.

**Comment by fonsp** [comment]
> is it in the scope of Pluto to include this special case for LaTeXStrings within the Pluto codebase?

Great question! Indeed, at the start of the discussion about LaTeXStrings, I would have said no, but recently we were able to easily add "integration" support code like the one you suggestion, with a system similar to Requires.jl. Let's wait to see what the LaTeXStrings friends decide to do, and otherwise we can add it.

Thanks for opening the issue at LaTeXStrings!

**Comment by fonsp** [comment]
Thanks! Let's continue waiting for LaTeXString (see my comment on your issue) and implement this in the meantime

**Pull request merged**
