### PR TITLE
End-to-end test improvements and fixes

### PR DESCRIPTION
**Pull request by novoselrok**
* Fixed the failing tests
* Improved entering text and other keyboard events into pluto input

### CODE REVIEW

**Comment by novoselrok** [comment]
Hopefully I can get a few green commits in a row to see if the flakiness has been eliminated.

**Comment by fonsp** [comment]
Would it be useful to use expose some internal things like:
https://github.com/fonsp/Pluto.jl/blob/v0.12.9/frontend/components/Editor.js#L211
or
the `.then` of the first request:
https://github.com/fonsp/Pluto.jl/blob/v0.12.9/frontend/components/Editor.js#L470

**Comment by novoselrok** [comment]
@fonsp Finally managed to get a couple of green commits in a row. You can use a squash merge for this PR to avoid having my empty trigger commits in git history.

**Comment by novoselrok** [comment]
Nice 👍

**Pull request merged**
