### PR TITLE
🔠 Replace Roboto Mono with JuliaMono

### PR DESCRIPTION
**Pull request by novoselrok**
Fixes: https://github.com/fonsp/Pluto.jl/issues/296

### CODE REVIEW

**Comment by fonsp** [comment]
We should measure the performance impact.

Can you take measurements before and after the change using Chrome devtools and post the screenshots here?

The two different times are:
1. Load time on first load (with cache disabled - check the Network log)
2. Load time on second load, with the service worker cache enabled (default)

So 4 timings in total

**Comment by novoselrok** [comment]
Measurements on the sample Tower of Hanoi notebook.

**Summary**

|                 |           | Load (ms) | DomContentLoaded (ms) |
|-----------------|-----------|-----------|-----------------------|
| Cache disabled  | Master    | 726       | 316                   |
|                 | JuliaMono | 1200      | 322                   |
| Cache/SW enabled   | Master    | 376       | 360                   |
|                 | JuliaMono | 391       | 362                   |

**Screenshots**

Master - cache disabled:

juliamono-cache-disabled

Master - cache enabled:

juliamono-cache-enabled

JuliaMono - cache disabled:

juliamono-cache-disabled

JuliaMono - cache enabled:

juliamono-cache-enabled

**Comment by fonsp** [comment]
Oof that's a lot. 

But actually, maybe `load` is measured until all fonts are loaded? In that case it's what we expected, and why we deliberately moved the latin subset out of the rest. The goal is that there will be a long load time, but the "time-to-first-juliamono-latin" is roughly the same as the current "time-to-first-robotomono". 

What do you think?

**Comment by novoselrok** [comment]
I think you are correct, `load` is until all fonts are downloaded. Additionally, I had to swap the order of Latin and regular fonts when specifying the `font-family`, so that Latin font gets downloaded first and then swapped if there are missing characters.

Now the "time-to-first-juliamono-latin" is roughly the same as the "time-to-first-robotomono".

**Comment by fonsp** [comment]
Shouldn't it be a single font-face, with the latin subset defined only on a unicode subset?

Like @Pocket-titan suggested in https://github.com/fonsp/Pluto.jl/issues/296#issuecomment-675136703

Or does a single font-face need to be loaded entirely before it is applied to the page?

You can use this to simulate a super slow response for the non-latin font files:
http://slowwly.robertomurray.co.uk/

**Comment by fonsp** [comment]
Another thing - I also use the Tower of Hanoi sample for my performance tests, but you need to test it on a page that contains non-latin characters inside code.

**Comment by novoselrok** [comment]
It's not a problem, this is a really fun project and I hope I can contribute some more in the future :slightly_smiling_face: 

You are correct regarding the unicode range. I was able to merge the two font families into one and everything is working the same.

For testing: I'm using a slightly modified version of the Hanoi notebook with a couple of non-latin cells. And I'm using the Chrome DevTools network throttling to test the font loading on slower connections.

**Comment by fonsp** [comment]
Great! So what are the test results for loading just the latin set?

**Comment by novoselrok** [comment]
I re-ran the tests on master as well. As far as I can measure, the JuliaMono Latin-only times are essentially the same to the Roboto Mono loading times.

|                 |           | Load (ms) | DomContentLoaded (ms) |
|-----------------|-----------|-----------|-----------------------|
| Cache disabled  | Master    | 733       | 319                   |
|                 | JuliaMono (Latin only) | 784      | 332                   |
| Cache/SW enabled   | Master    | 386       | 330                   |
|                 | JuliaMono (Latin only) | 393       | 375                   |

**Comment by fonsp** [comment]
🎉

**Comment by fonsp** [comment]
@cormullion

**Comment by fonsp** [comment]
Nice! I'm still not 100% satisfied with how the UI (top and bottom) looks with the new font, but I'll come back to it later

**Comment by cormullion** [comment]
wow thanks a lot everyone! I’m very honoured to play a small part in Pluto’s early development! Definitely makes it worthwhile. 

You’re linking to a specific version (v0.013) for safety, I suppose? Currently I appear to be making one release a week, which obviously won’t last... v0.015 will have BoldLatin perhaps 😂

**Comment by fonsp** [comment]
Okay! I will subscribe to your releases and update it here - I also release once a week :)

**Comment by novoselrok** [comment]
@fonsp Do you want me to update anything else, or will you just finish up the UI tweaks?

**Comment by fonsp** [comment]
Let's use Roboto Mono for UI (header+footer) and JuliaMono for the codemirrors

**Comment by fonsp** [comment]
💕

**Comment by fonsp** [comment]
This is awesome!

image

**Comment by novoselrok** [comment]
🎉🔥

**Comment by cormullion** [comment]
UnicodePlots is great - try `heatmap()` as well!

**Comment by jtschneider** [comment]
Quick note about Roboto: The glyph for x and χ are the same in Roboto, which can be seen [here](https://fonts.google.com/specimen/Roboto+Mono?preview.text=%CF%87x&preview.text_type=custom&category=Monospace). This costed me some annoyance since I had code with x and χ , see also https://github.com/fonsp/Pluto.jl/issues/1071 .
I would therefore lobby for changing the font towards a font that has actually different glyphs for different (and often used) unicode characters, for example Fira Mono.

**Comment by fonsp** [comment]
@jtschneider Do not cross-post to get more attention

**Comment by KronosTheLate** [comment]
> UnicodePlots is great - try `heatmap()` as well!

That is what brought me here - an issue with heatmap unicode plots. The output in VSCode:
image

The output in Pluto:
image

Should I open a seperate issue for it, or is it enough to ping the relevant people by this comment?

**Comment by cormullion** [comment]
This is a duplicate of https://github.com/fonsp/Pluto.jl/issues/894, I think.

**Comment by KronosTheLate** [comment]
Looks like. Thanks for the quick reply - It looks like the issue is being properly handled over there.

**Pull request merged**
